CHECK_INCLUDE_FILE (vorbis/codec.h	HAVE_VORBIS_CODEC_H)
CHECK_INCLUDE_FILE (vorbis/vorbisenc.h	HAVE_VORBIS_VORBISENC_H)
CHECK_INCLUDE_FILE (speex/speex.h	HAVE_SPEEX_SPEEX_H)

CHECK_LIBRARY_EXISTS (ogg	ogg_sync_buffer			"" HAVE_LIB_OGG)
CHECK_LIBRARY_EXISTS (vorbis	vorbis_synthesis_headerin	"" HAVE_LIB_VORBIS)
CHECK_LIBRARY_EXISTS (speex	speex_packet_to_header		"" HAVE_LIB_SPEEX)

IF (NOT HAVE_VORBIS_CODEC_H OR NOT HAVE_VORBIS_VORBISENC_H OR NOT HAVE_SPEEX_SPEEX_H OR NOT HAVE_LIB_OGG OR NOT HAVE_LIB_VORBIS OR NOT HAVE_LIB_SPEEX)
    DISABLE_PLUGIN ()
ENDIF ()
