include ../../Makefile.plugin

# Special CFLAGS and OFLAGS
CFLAGS+= -Werror-implicit-function-declaration
OFLAGS=-O0

# Special OFLAGS for some files
#k_tan.o: k_tan.c
#	$(MAKE) -f ../../Makefile.plugin OFLAGS="-O0" $*.o
#
#acos.o: acos.c
#	$(MAKE) -f ../../Makefile.plugin OFLAGS="-O0" $*.o
#
#tanh.o: tanh.c
#	$(MAKE) -f ../../Makefile.plugin OFLAGS="-O0" $*.o
#
