#!/bin/bash
INSTALLDIR=nsvmlinux
if [ $# -ge 1 ]; then
	INSTALLDIR="$1"; shift
fi
# Some gcc versions create a broken VM using -O2
case `gcc -v 2>&1 | grep version | sed 's/gcc version *//'` in
3.4.*)	OPT=-O1;;
*)		OPT=-O2;;
esac

echo -n "clean? "
read a
case $a in
n|no|N|NO)	echo "ok but this isn't safe!!";;
*)			make reallyclean
esac
test -f config.h || ../../../platforms/unix/config/configure --with-src=nscogsrc \
	--without-vm-display-fbdev --without-npsqueak \
	CC="gcc -m32" \
	CFLAGS="-g $OPT -msse2 -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -DNDEBUG -DITIMER_HEARTBEAT=1 -DNO_VM_PROFILE=1 -DMULTIPLEBYTECODESETS=1 -DDEBUGVM=0" \
	LIBS="-lpthread -luuid" \
	LDFLAGS=-Wl,-z,now
../../../scripts/nukeversion
rm -rf ../../../$INSTALLDIR
# would prefer make install prefix=`readlink -f \`pwd\`/../../../$INSTALLDIR`
# but older linux readlinks lack the -f flag
make install prefix=`(cd ../../../;pwd)`/$INSTALLDIR
(cd ../../../$INSTALLDIR
 if [ -f squeak ]; then
        mv squeak nsvm
        ex -u NONE "+g/squeak/s/squeak/nsvm/g" +w +q nsvm
  fi
  if [ -f bin/squeak ]; then
        mv bin/squeak bin/nsvm
        ex -u NONE "+g/squeak/s/squeak/nsvm/g" +w +q bin/nsvm
  fi
  rm -rf man doc
  LIBDIR="`echo lib/squeak/[0-9.-]*`"
  test -f $LIBDIR/squeak && mv $LIBDIR/squeak $LIBDIR/nsvm
  test -d lib/squeak && mv lib/squeak lib/nsvm
  LIBDIR="`echo lib/nsvm/[0-9.-]*`"
  if [ "$1" = -copysource ]; then
	cp ~/Squeak/SqueakV41.sources $LIBDIR
  elif [ -h ~/Squeak/SqueakV41.sources ]; then
	ln "`readlink ~/Squeak/SqueakV41.sources`" $LIBDIR
  elif [ -f ~/Squeak/SqueakV41.sources ]; then
	ln ~/Squeak/SqueakV41.sources $LIBDIR
  else
	echo "can't find SqueakV41.sources" 1>&2
  fi)
