/* Automatically generated by
	CCodeGeneratorGlobalStructure VMMaker.oscog-eem.1993 uuid: b98dd9d4-1e93-4aa8-bd46-5ac460a44262
 */

#define VM_PROXY_MAJOR 1
#define VM_PROXY_MINOR 13

#define SQ_VI_BYTES_PER_WORD 4

#define BaseHeaderSize 4
#define BytesPerOop 4
#define BytesPerWord 4

#define PrimErrGenericFailure 1
#define PrimErrBadReceiver 2
#define PrimErrBadArgument 3
#define PrimErrBadIndex 4
#define PrimErrBadNumArgs 5
#define PrimErrInappropriate 6
#define PrimErrUnsupported 7
#define PrimErrNoModification 8
#define PrimErrNoMemory 9
#define PrimErrNoCMemory 10
#define PrimErrNotFound 11
#define PrimErrBadMethod 12
#define PrimErrNamedInternal 13
#define PrimErrObjectMayMove 14
#define PrimErrLimitExceeded 15
#define PrimErrObjectIsPinned 16
#define PrimErrWritePastObject 17

#define MinSmallInteger -1073741824
#define MaxSmallInteger 1073741823
#define NumSmallIntegerTagBits 1

#define STACKVM 1
#define COGVM 1
#if !defined(COGMTVM)
#	define COGMTVM 0
#endif

#define DisownVMLockOutFullGC 1
