/* Automatically generated by
	SmartSyntaxPluginCodeGenerator VMMaker.oscog-eem.222 uuid: 9255d122-7216-4700-8ead-493416ce0cf6
   from
	QuicktimePlugin VMMaker.oscog-eem.222 uuid: 9255d122-7216-4700-8ead-493416ce0cf6
 */
static char __buildInfo[] = "QuicktimePlugin VMMaker.oscog-eem.222 uuid: 9255d122-7216-4700-8ead-493416ce0cf6 " __DATE__ ;



#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

/* Default EXPORT macro that does nothing (see comment in sq.h): */
#define EXPORT(returnType) returnType

/* Do not include the entire sq.h file but just those parts needed. */
/*  The virtual machine proxy definition */
#include "sqVirtualMachine.h"
/* Configuration options */
#include "sqConfig.h"
/* Platform specific definitions */
#include "sqPlatformSpecific.h"

#define true 1
#define false 0
#define null 0  /* using 'null' because nil is predefined in Think C */
#ifdef SQUEAK_BUILTIN_PLUGIN
#undef EXPORT
// was #undef EXPORT(returnType) but screws NorCroft cc
#define EXPORT(returnType) static returnType
#endif

#include "QuicktimePlugin.h"
#include "sqMemoryAccess.h"


/*** Constants ***/
#define BytesPerWord 4


/*** Function Prototypes ***/
static VirtualMachine * getInterpreter(void);
EXPORT(const char*) getModuleName(void);
static sqInt halt(void);
EXPORT(sqInt) initialiseModule(void);
EXPORT(void) moduleUnloaded(char *aModuleName);
static sqInt msg(char *s);
EXPORT(sqInt) primitiveClearFrameCompletedSemaphore(void);
EXPORT(sqInt) primitiveDestroyHandle(void);
EXPORT(sqInt) primitiveDestroySurface(void);
EXPORT(sqInt) primitiveSetFrameCompletedSemaphore(void);
EXPORT(sqInt) primitiveSetGWorldPtrOntoExistingSurface(void);
EXPORT(sqInt) primitiveSetGWorldPtrOntoSurface(void);
EXPORT(sqInt) setInterpreter(struct VirtualMachine*anInterpreter);
static void sqAssert(sqInt aBool);


/*** Variables ***/

#ifdef SQUEAK_BUILTIN_PLUGIN
extern
#endif
struct VirtualMachine* interpreterProxy;
static const char *moduleName =
#ifdef SQUEAK_BUILTIN_PLUGIN
	"QuicktimePlugin VMMaker.oscog-eem.222 (i)"
#else
	"QuicktimePlugin VMMaker.oscog-eem.222 (e)"
#endif
;



/*	Note: This is coded so that plugins can be run from Squeak. */

static VirtualMachine *
getInterpreter(void)
{
	return interpreterProxy;
}


/*	Note: This is hardcoded so it can be run from Squeak.
	The module name is used for validating a module *after*
	it is loaded to check if it does really contain the module
	we're thinking it contains. This is important! */

EXPORT(const char*)
getModuleName(void)
{
	return moduleName;
}

static sqInt
halt(void)
{
	;
	return 0;
}

EXPORT(sqInt)
initialiseModule(void)
{
	return sqQuicktimeInitialize();
}


/*	The module with the given name was just unloaded. 
	Make sure we have no dangling references. */

EXPORT(void)
moduleUnloaded(char *aModuleName)
{
	if ((strcmp(aModuleName, "QuicktimePlugin")) == 0) {
		sqQuicktimeShutdown();
	}
}

static sqInt
msg(char *s)
{
	fprintf(stderr, "\n%s: %s", moduleName, s);
	return 0;
}

EXPORT(sqInt)
primitiveClearFrameCompletedSemaphore(void)
{
	sqInt data;

	data = interpreterProxy->stackIntegerValue(0);
	if (interpreterProxy->failed()) {
		return null;
	}
	stQuicktimeClearSemaphore(data);
	return null;
}

EXPORT(sqInt)
primitiveDestroyHandle(void)
{
	sqInt data;

	data = interpreterProxy->stackIntegerValue(0);
	if (interpreterProxy->failed()) {
		return null;
	}
	stQuicktimeDestroy(data);
	return null;
}

EXPORT(sqInt)
primitiveDestroySurface(void)
{
	sqInt data;

	data = interpreterProxy->stackIntegerValue(0);
	if (interpreterProxy->failed()) {
		return null;
	}
	stQuicktimeDestroySurface(data);
	return null;
}

EXPORT(sqInt)
primitiveSetFrameCompletedSemaphore(void)
{
	sqInt data;
	sqInt semaIndex;

	semaIndex = interpreterProxy->stackIntegerValue(1);
	data = interpreterProxy->stackIntegerValue(0);
	if (interpreterProxy->failed()) {
		return null;
	}
	stQuicktimeSetSemaphorefor(semaIndex, data);
	return null;
}

EXPORT(sqInt)
primitiveSetGWorldPtrOntoExistingSurface(void)
{
	sqInt bitMapPtr;
	sqInt buffer;
	sqInt depth;
	sqInt height;
	sqInt movie;
	sqInt moviePtr;
	sqInt rowBytes;
	sqInt surfaceID;
	sqInt width;

	surfaceID = interpreterProxy->stackIntegerValue(6);
	bitMapPtr = interpreterProxy->stackValue(5);
	width = interpreterProxy->stackIntegerValue(4);
	height = interpreterProxy->stackIntegerValue(3);
	rowBytes = interpreterProxy->stackIntegerValue(2);
	depth = interpreterProxy->stackIntegerValue(1);
	moviePtr = interpreterProxy->stackValue(0);
	if (interpreterProxy->failed()) {
		return null;
	}
	buffer = ((char *) (interpreterProxy->positive32BitValueOf(bitMapPtr)));
	movie = ((long) (interpreterProxy->positive32BitValueOf(moviePtr)));
	stQuicktimeSetToExistingSurfacegworldwidthheightrowBytesdepthmovie(surfaceID, buffer, width, height, rowBytes, depth, movie);
	if (interpreterProxy->failed()) {
		return null;
	}
	interpreterProxy->pop(7);
	return null;
}

EXPORT(sqInt)
primitiveSetGWorldPtrOntoSurface(void)
{
	sqInt bitMapPtr;
	sqInt buffer;
	sqInt depth;
	sqInt height;
	sqInt movie;
	sqInt moviePtr;
	sqInt results;
	sqInt rowBytes;
	sqInt width;
	sqInt _return_value;

	bitMapPtr = interpreterProxy->stackValue(5);
	width = interpreterProxy->stackIntegerValue(4);
	height = interpreterProxy->stackIntegerValue(3);
	rowBytes = interpreterProxy->stackIntegerValue(2);
	depth = interpreterProxy->stackIntegerValue(1);
	moviePtr = interpreterProxy->stackValue(0);
	if (interpreterProxy->failed()) {
		return null;
	}
	buffer = ((char *) (interpreterProxy->positive32BitValueOf(bitMapPtr)));
	movie = ((long) (interpreterProxy->positive32BitValueOf(moviePtr)));
	results = stQuicktimeSetSurfacewidthheightrowBytesdepthmovie(buffer, width, height, rowBytes, depth, movie);
	_return_value = interpreterProxy->integerObjectOf(results);
	if (interpreterProxy->failed()) {
		return null;
	}
	interpreterProxy->popthenPush(7, _return_value);
	return null;
}


/*	Note: This is coded so that is can be run from Squeak. */

EXPORT(sqInt)
setInterpreter(struct VirtualMachine*anInterpreter)
{
	sqInt ok;

	interpreterProxy = anInterpreter;
	ok = interpreterProxy->majorVersion() == VM_PROXY_MAJOR;
	if (ok == 0) {
		return 0;
	}
	ok = interpreterProxy->minorVersion() >= VM_PROXY_MINOR;
	return ok;
}

static void
sqAssert(sqInt aBool)
{
	/* missing DebugCode */;
}


#ifdef SQUEAK_BUILTIN_PLUGIN

void* QuicktimePlugin_exports[][3] = {
	{"QuicktimePlugin", "getModuleName", (void*)getModuleName},
	{"QuicktimePlugin", "initialiseModule", (void*)initialiseModule},
	{"QuicktimePlugin", "moduleUnloaded", (void*)moduleUnloaded},
	{"QuicktimePlugin", "primitiveClearFrameCompletedSemaphore", (void*)primitiveClearFrameCompletedSemaphore},
	{"QuicktimePlugin", "primitiveDestroyHandle", (void*)primitiveDestroyHandle},
	{"QuicktimePlugin", "primitiveDestroySurface", (void*)primitiveDestroySurface},
	{"QuicktimePlugin", "primitiveSetFrameCompletedSemaphore", (void*)primitiveSetFrameCompletedSemaphore},
	{"QuicktimePlugin", "primitiveSetGWorldPtrOntoExistingSurface", (void*)primitiveSetGWorldPtrOntoExistingSurface},
	{"QuicktimePlugin", "primitiveSetGWorldPtrOntoSurface", (void*)primitiveSetGWorldPtrOntoSurface},
	{"QuicktimePlugin", "setInterpreter", (void*)setInterpreter},
	{NULL, NULL, NULL}
};

#endif /* ifdef SQ_BUILTIN_PLUGIN */
