/* Automatically generated by
	ThreadedFFIPlugin VMMaker.oscog-eem.920 uuid: cfdfcd30-b5f8-4c49-a6b4-2c55bd7a3b6c
 */

#if defined(__ARM_ARCH__) || defined(__arm__) || defined(__arm32__) || defined(ARM32)

#	include "ARM32FFIPlugin.c"

#elif defined(_M_I386) || defined(_X86_) || defined(i386) || defined(i486) || defined(i586) || defined(i686) || defined(__i386__) || defined(__386__) || defined(X86) || defined(I386)

#	include "IA32FFIPlugin.c"

#else
#	error As yet no FFI implementation appears to exist for your platform.
#	error Consider implementing it, starting by adding a subclass of ThreadedFFIPlugin.
#endif
