#!/usr/bin/env bash
set -e
case "`uname -m`" in # ensure we see x86 as machine type
i*86) ;; # we're good
*) if type i386 2>&1 >/dev/null; then
	echo "Re-exec as x86"
	exec i386 "$0" "$@"
fi ;;
esac
# assert VM with VM profiler and threaded heartbeat
INSTALLDIR=assert/phsistaspur32linuxht
OPT="-g3 -O1 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -DDEBUGVM=0 -DPharoVM"

if [ $# -ge 1 ]; then
	INSTALLDIR="$1"; shift
fi

if ../../../../scripts/checkSCCSversion ; then exit 1; fi
echo -n "clean? "
read a
case $a in
n|no|N|NO)	echo "ok but this isn't safe!!";;
*)			test -f Makefile && make reallyclean
esac

../../../../scripts/copylinuxpluginspecfiles

test -f config.h || ../../../../platforms/unix/config/configure \
		--without-npsqueak \
		--with-vmversion=5.0 \
		--with-src=src/spur32.sista \
	TARGET_ARCH="-m32" \
	CFLAGS="$OPT -msse2 -DCOGMTVM=0" \
	LDFLAGS="-Wl,-rpath,'\$\$ORIGIN' "
rm -f vm/sqUnixMain.o # nuke version info
rm -rf ../../../../products/$INSTALLDIR
# prefer make install prefix=`readlink -f \`pwd\`/../../../../products/$INSTALLDIR`
# but older linux readlinks lack the -f flag
make install-squeak install-plugins prefix=`(cd ../../../../;pwd)`/products/$INSTALLDIR 2>&1 | tee LOG ; test ${PIPESTATUS[0]} -eq 0
productDir=`find ../../../../products/$INSTALLDIR -name "5.0*"`
productDir=`(cd $productDir;pwd)`
for lib in ${THIRDPARTYLIBS}; do
	../../third-party/mvm ${lib} install $productDir
done
../../editpharoinstall.sh ../../../../products/$INSTALLDIR "$@"
