#############################################################################
# Makefile for Win32 Cog Spur Squeak VM using gcc-3.4.x and cygwin
# Do make init to allow make -n to function.
#############################################################################

VM:=Squeak
VMSRCDIR:=../../spursistasrc/vm

include ../common/Makefile
