INCLUDE_DIRECTORIES (${cross}/plugins/B3DAcceleratorPlugin ${cross}/plugins/FilePlugin ${OPENGL_INCLUDE_DIR})
TARGET_LINK_LIBRARIES (@plugin@ ${X11_LIBRARIES} ${OPENGL_LIBRARIES})
EXPECT_UNDEFINED_SYMBOLS ()
