/* Automatically generated by
	Cogit VMMaker.oscog-eem.2174 uuid: eefef0d3-2df8-4fe7-9f71-2aca68641ba6
 */

#if !SysVABI && !WIN64ABI
# define SysVABI 1
#endif

#if SysVABI && (defined(x86_64) || defined(__amd64) || defined(__x86_64) || defined(__amd64__) || defined(__x86_64__) || defined(_M_AMD64) || defined(_M_X64))

#	include "cogitX64SysV.c"

#elif WIN64ABI && (defined(x86_64) || defined(__amd64) || defined(__x86_64) || defined(__amd64__) || defined(__x86_64__) || defined(_M_AMD64) || defined(_M_X64))

#	include "cogitX64WIN64.c"

#else
#	error As yet no Cogit implementation appears to exist for your platform.
#	error Consider implementing it, starting by adding a subclass of CogAbstractInstruction.
#endif
