/* Automatically generated by
	Cogit VMMaker.oscog-eem.2596 uuid: 8500baf3-a5ae-4594-9f3b-08cedfdf1fb3
 */

#if !SysV && !_WIN64
# define SysV 1
#endif

#if defined(__ARM_ARCH_8__) || defined(__arm__) || defined(__arm64__) || defined(ARM64)

#	include "cogitARMv8.c"

#elif SysV && (defined(x86_64) || defined(__amd64) || defined(__x86_64) || defined(__amd64__) || defined(__x86_64__) || defined(_M_AMD64) || defined(_M_X64))

#	include "cogitX64SysV.c"

#elif _WIN64 && (defined(x86_64) || defined(__amd64) || defined(__x86_64) || defined(__amd64__) || defined(__x86_64__) || defined(_M_AMD64) || defined(_M_X64))

#	include "cogitX64WIN64.c"

#else
#	error As yet no Cogit implementation appears to exist for your platform.
#	error Consider implementing it, starting by adding a subclass of CogAbstractInstruction.
#endif
