##############################################################################
# Makefile for Mac OS X Stack Spur Newspeak Cocoa VM using clang and gnu make 3.81
# Do make init to allow make -n to function.
#

VMSRCDIR:= ../../nsspurstacksrc/vm

include ../common/Makefile.app.newspeak
