.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2013 Damien Cassou <damien.cassou@gmail.com>,
.\"
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH PHARO 1 "April 2013" "PHARO" "Pharo" "User Commands"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
pharo7-32 \- A clean and innovative Smalltalk-inspired environment.
.SH SYNOPSIS
.B pharo
[\fI<option>\fR...] [\fI<imageName> \fR[\fI<argument>\fR...]]
.SH DESCRIPTION
.IP
.SS "X11 <option>s:"
.TP
\fB\-browserWindow\fR <wid>
run in window <wid>
.HP
\fB\-browserPipes\fR <r> <w> run as Browser plugin using descriptors <r> <w>
.TP
\fB\-cmdmod\fR <n>
map Mod<n> to the Command key
.TP
\fB\-compositioninput\fR
enable overlay window for composed characters
.TP
\fB\-display\fR <dpy>
display on <dpy> (default: $DISPLAY)
.TP
\fB\-fullscreen\fR
occupy the entire screen
.TP
\fB\-glxdebug\fR <n>
set GLX debug verbosity level to <n>
.TP
\fB\-headless\fR
run in headless (no window) mode
.TP
\fB\-iconic\fR
start up iconified
.TP
\fB\-lazy\fR
go to sleep when main window unmapped
.TP
\fB\-mapdelbs\fR
map Delete key onto Backspace
.TP
\fB\-nointl\fR
disable international keyboard support
.TP
\fB\-notitle\fR
disable the Pharo window title bar
.TP
\fB\-title\fR <t>
use t as the Pharo window title instead of the image name
.TP
\fB\-ldtoms\fR <n>
launch drop timeout milliseconds
.TP
\fB\-noxdnd\fR
disable X drag\-and\-drop protocol support
.TP
\fB\-optmod\fR <n>
map Mod<n> to the Option key
.TP
\fB\-swapbtn\fR
swap yellow (middle) and blue (right) buttons
.TP
\fB\-xasync\fR
don't serialize display updates
.TP
\fB\-xicfont\fR <f>
use font set <f> for the input context overlay
.TP
\fB\-xshm\fR
use X shared memory extension
.SS "Common <option>s:"
.TP
\fB\-encoding\fR <enc>
set the internal character encoding (default: MacRoman)
.TP
\fB\-help\fR
print this help message, then exit
.TP
\fB\-memory\fR <size>[mk]
use fixed heap size (added to image size)
.TP
\fB\-mmap\fR <size>[mk]
limit dynamic heap size (default: 1024m)
.TP
\fB\-timephases\fR
print start load and run times
.TP
\fB\-breaksel\fR selector
set breakpoint on send of selector
.TP
\fB\-eden\fR <size>[mk]
use given eden size
.TP
\fB\-leakcheck\fR num
check for leaks in the heap
.TP
\fB\-stackpages\fR <num>
use given number of stack pages
.TP
\fB\-noevents\fR
disable event\-driven input support
.TP
\fB\-nohandlers\fR
disable sigsegv & sigusr1 handlers
.TP
\fB\-pollpip\fR
output . on each poll for input
.TP
\fB\-pathenc\fR <enc>
set encoding for pathnames (default: UTF\-8)
.TP
\fB\-plugins\fR <path>
specify alternative plugin location (see manpage)
.TP
\fB\-textenc\fR <enc>
set encoding for external text (default: UTF\-8)
.TP
\fB\-version\fR
print version information, then exit
.TP
\fB\-vm\-\fR<sys>\-<dev>
use the <dev> driver for <sys> (see below)
.TP
\fB\-trace\fR[=\fInum\fR]
enable tracing (optionally to a specific value)
.TP
\fB\-codesize\fR <size>[mk]
set machine code memory to bytes
.TP
\fB\-tracestores\fR
enable store tracing (assert check stores)
.TP
\fB\-cogmaxlits\fR <n>
set max number of literals for methods compiled to machine code
.TP
\fB\-cogminjumps\fR <n>
set min number of backward jumps for interpreted methods to be considered for compilation to machine code
.TP
\fB\-blockonerror\fR
on error or segv block, not exit.  useful for attaching gdb
.SS "Deprecated:"
.TP
\fB\-notimer\fR
disable interval timer for low\-res clock
.TP
\fB\-display\fR <dpy>
equivalent to '\-vm\-display\-X11 \fB\-display\fR <dpy>'
.TP
\fB\-headless\fR
equivalent to '\-vm\-display\-X11 \fB\-headless\fR'
.TP
\fB\-nodisplay\fR
equivalent to '\-vm\-display\-null'
.TP
\fB\-nomixer\fR
disable modification of mixer settings
.TP
\fB\-nosound\fR
equivalent to '\-vm\-sound\-null'
.TP
\fB\-quartz\fR
equivalent to '\-vm\-display\-Quartz'
.SS "Notes:"
.IP
<imageName> defaults to `pharo.image'.
Using `unix:0' for <dpy> may improve local display performance.
\fB\-xshm\fR only works when Pharo is running on the X server host.
If `\-memory' is not specified then the heap will grow dynamically.
<argument>s are ignored, but are processed by the pharo image.
The first <argument> normally names a pharo `script' to execute.
Precede <arguments> by `\-\-' to use default image.
.SS "Available drivers:"
.IP
vm\-sound\-null
vm\-sound\-ALSA
vm\-display\-null
vm\-display\-X11
.SH BUGS
No known bugs (what did you expect?).
.SH AUTHOR
Damien Cassou (damien.cassou@gmail.com)
