/* Automatically generated by
	SmartSyntaxPluginCodeGenerator VMMaker.oscog-eem.3739 uuid: 2d2f2ceb-57d6-4381-b5c9-1a3f4bc795de
	(Compiler-ct.529)
   from
	BochsIA32Plugin Cog-eem.508 uuid: 5c76b389-85ab-4854-abac-36ec350399e5
 */
static char __buildInfo[] = "BochsIA32Plugin Cog-eem.508 uuid: 5c76b389-85ab-4854-abac-36ec350399e5 " __DATE__ ;


#include "config.h"
#include <math.h>
#include "sqMathShim.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

/* Do not include the entire sq.h file but just those parts needed. */
#include "sqConfig.h"			/* Configuration options */
#include "sqVirtualMachine.h"	/*  The virtual machine proxy definition */
#include "sqPlatformSpecific.h"	/* Platform specific definitions */

#include "BochsIA32Plugin.h"
#include "sqMemoryAccess.h"

#define true 1
#define false 0
#define null 0  /* using 'null' because nil is predefined in Think C */
#ifdef SQUEAK_BUILTIN_PLUGIN
# undef EXPORT
# define EXPORT(returnType) static returnType
# define INT_EXT "(i)"
#else
# define INT_EXT "(e)"
#endif


/* ProcessorSimulatorPlugin class>>preambleCCode */

# define isIntegerObject(oop) ((oop) & 1)
# define integerObjectOf(value) ((((usqInt) value) << NumSmallIntegerTagBits) | 1)
# define integerValueOf(oop) ((oop) >> NumSmallIntegerTagBits)

# if SPURVM
extern sqInt classIndexOf(sqInt);
#	define LargeNegativeIntegerClassIndex 32
#	define LargePositiveIntegerClassIndex 33
#	if BytesPerOop == 4
#	  define isImmediate(oop) ((oop) & 3)
#	else
#	  define isImmediate(oop) ((oop) & 7)
#	endif
#	define isKindOfInteger(oop) (isImmediate(oop) ? isIntegerObject(oop) : (unsigned)(classIndexOf(oop) - LargeNegativeIntegerClassIndex) <= 1)
#	define isLargeIntegerObject(oop) (!isImmediate(oop) && (unsigned)(classIndexOf(oop) - LargeNegativeIntegerClassIndex) <= 1)
#	define isLargeNegativeIntegerObject(oop) (!isImmediate(oop) && classIndexOf(oop) == LargeNegativeIntegerClassIndex)
#	define isLargePositiveIntegerObject(oop) (!isImmediate(oop) && classIndexOf(oop) == LargePositiveIntegerClassIndex)
# endif /* SPURVM */

#if !defined(isKindOfInteger)
# define isLargeNegativeIntegerObject(oop) (fetchClassOf(oop) == classLargeNegativeInteger())
# define isLargePositiveIntegerObject(oop) (fetchClassOf(oop) == classLargePositiveInteger())
# define isLargeIntegerObject(oop) (isLargeNegativeIntegerObject(oop) || isLargePositiveIntegerObject(oop))
# define isKindOfInteger(oop) (isIntegerObject(oop) || isLargeNegativeIntegerObject(oop) || isLargePositiveIntegerObject(oop))
#endif

/* end ProcessorSimulatorPlugin class>>preambleCCode */


/*** Function Prototypes ***/
static void forceStopOnInterrupt(void);
EXPORT(const char*) getModuleName(void);
EXPORT(sqInt) primitive64BitPerformanceCounter(void);
EXPORT(sqInt) primitiveDisassembleAtInMemory(void);
EXPORT(sqInt) primitiveDisassembleWithAddressAtInMemory(void);
EXPORT(sqInt) primitiveDisassembleWithoutAddressAtInMemory(void);
EXPORT(sqInt) primitiveErrorAndLog(void);
EXPORT(sqInt) primitiveFlushICacheFromTo(void);
EXPORT(sqInt) primitiveIntegerRegisterState(void);
EXPORT(sqInt) primitiveMemoryOffset(void);
EXPORT(sqInt) primitiveNewCPU(void);
EXPORT(sqInt) primitivePrintInstructionBytes(void);
EXPORT(sqInt) primitiveRelevantRegisterState(void);
EXPORT(sqInt) primitiveResetCPU(void);
EXPORT(sqInt) primitiveRunInMemoryMinAddressMaxAddressReadWrite(void);
EXPORT(sqInt) primitiveRunInMemoryMinimumAddressReadWrite(void);
EXPORT(sqInt) primitiveRunInMemoryOffsetMinimumAddressReadWrite(void);
EXPORT(sqInt) primitiveSingleStepInMemoryMinAddressMaxAddressReadWrite(void);
EXPORT(sqInt) primitiveSingleStepInMemoryMinimumAddressReadWrite(void);
EXPORT(sqInt) primitiveSingleStepInMemoryOffsetMinimumAddressReadWrite(void);
EXPORT(sqInt) setInterpreter(struct VirtualMachine *anInterpreter);


/*** Variables ***/

#if !defined(SQUEAK_BUILTIN_PLUGIN)
static sqInt (*booleanValueOf)(sqInt obj);
static sqInt (*byteSizeOf)(sqInt oop);
static sqInt (*classArray)(void);
#if VM_PROXY_MAJOR > 1 || (VM_PROXY_MAJOR == 1 && VM_PROXY_MINOR >= 16)
static sqInt (*classDoubleWordArray)(void);
#else
# define classDoubleWordArray() 0
#endif
static sqInt (*classString)(void);
#if VM_PROXY_MAJOR > 1 || (VM_PROXY_MAJOR == 1 && VM_PROXY_MINOR >= 16)
static sqInt (*classWordArray)(void);
#else
# define classWordArray() 0
#endif
static sqInt (*failed)(void);
static void * (*firstIndexableField)(sqInt oop);
static sqInt (*getInterruptPending)(void);
static sqInt (*instantiateClassindexableSize)(sqInt classPointer, sqInt size);
#if !defined(integerValueOf)
static sqInt (*integerValueOf)(sqInt oop);
#endif
#if VM_PROXY_MAJOR > 1 || (VM_PROXY_MAJOR == 1 && VM_PROXY_MINOR >= 15)
static sqInt (*isBooleanObject)(sqInt oop);
#else
# define isBooleanObject(oop) 0
#endif
#if !defined(isIntegerObject)
static sqInt (*isIntegerObject)(sqInt objectPointer);
#endif
static sqInt (*isWordsOrBytes)(sqInt oop);
static sqInt (*methodArgumentCount)(void);
static sqInt (*methodReturnBool)(sqInt boolean);
static sqInt (*methodReturnInteger)(sqInt integer);
static sqInt (*methodReturnReceiver)(void);
static sqInt (*methodReturnValue)(sqInt oop);
static sqInt (*nilObject)(void);
static sqInt (*pop)(sqInt nItems);
static sqInt (*popRemappableOop)(void);
static sqInt (*positive32BitIntegerFor)(unsigned int integerValue);
static sqInt (*positive64BitIntegerFor)(usqLong integerValue);
static usqLong (*positive64BitValueOf)(sqInt oop);
static sqInt (*primitiveFail)(void);
static sqInt (*primitiveFailFor)(sqInt reasonCode);
#if VM_PROXY_MAJOR > 1 || (VM_PROXY_MAJOR == 1 && VM_PROXY_MINOR >= 14)
static sqInt (*primitiveFailForOSError)(sqLong osErrorCode);
#else
# define primitiveFailForOSError(osErrorCode) 0
#endif
static sqInt (*pushRemappableOop)(sqInt oop);
static void * (*setInterruptCheckChain)(void (*aFunction)());
static sqInt (*stackValue)(sqInt offset);
static void (*storeIntegerofObjectwithValue)(sqInt index, sqInt oop, sqLong integer);
static sqInt (*storePointerofObjectwithValue)(sqInt index, sqInt oop, sqInt valuePointer);
#else /* !defined(SQUEAK_BUILTIN_PLUGIN) */
extern sqInt booleanValueOf(sqInt obj);
extern sqInt byteSizeOf(sqInt oop);
extern sqInt classArray(void);
#if VM_PROXY_MAJOR > 1 || (VM_PROXY_MAJOR == 1 && VM_PROXY_MINOR >= 16)
extern sqInt classDoubleWordArray(void);
#else
# define classDoubleWordArray() 0
#endif
extern sqInt classString(void);
#if VM_PROXY_MAJOR > 1 || (VM_PROXY_MAJOR == 1 && VM_PROXY_MINOR >= 16)
extern sqInt classWordArray(void);
#else
# define classWordArray() 0
#endif
extern sqInt failed(void);
extern void * firstIndexableField(sqInt oop);
extern sqInt getInterruptPending(void);
extern sqInt instantiateClassindexableSize(sqInt classPointer, sqInt size);
#if !defined(integerValueOf)
extern sqInt integerValueOf(sqInt oop);
#endif
#if VM_PROXY_MAJOR > 1 || (VM_PROXY_MAJOR == 1 && VM_PROXY_MINOR >= 15)
extern sqInt isBooleanObject(sqInt oop);
#else
# define isBooleanObject(oop) 0
#endif
#if !defined(isIntegerObject)
extern sqInt isIntegerObject(sqInt objectPointer);
#endif
extern sqInt isWordsOrBytes(sqInt oop);
extern sqInt methodArgumentCount(void);
extern sqInt methodReturnBool(sqInt boolean);
extern sqInt methodReturnInteger(sqInt integer);
extern sqInt methodReturnReceiver(void);
extern sqInt methodReturnValue(sqInt oop);
extern sqInt nilObject(void);
extern sqInt pop(sqInt nItems);
extern sqInt popRemappableOop(void);
extern sqInt positive32BitIntegerFor(unsigned int integerValue);
extern sqInt positive64BitIntegerFor(usqLong integerValue);
extern usqLong positive64BitValueOf(sqInt oop);
extern sqInt primitiveFail(void);
extern sqInt primitiveFailFor(sqInt reasonCode);
#if VM_PROXY_MAJOR > 1 || (VM_PROXY_MAJOR == 1 && VM_PROXY_MINOR >= 14)
extern sqInt primitiveFailForOSError(sqLong osErrorCode);
#else
# define primitiveFailForOSError(osErrorCode) 0
#endif
extern sqInt pushRemappableOop(sqInt oop);
extern void * setInterruptCheckChain(void (*aFunction)());
extern sqInt stackValue(sqInt offset);
extern void storeIntegerofObjectwithValue(sqInt index, sqInt oop, sqLong integer);
extern sqInt storePointerofObjectwithValue(sqInt index, sqInt oop, sqInt valuePointer);
extern
#endif
struct VirtualMachine* interpreterProxy;
static sqInt memoryOffset = 0;
static const char *moduleName = "BochsIA32Plugin Cog-eem.508 " INT_EXT;
int printInstructionBytes = 1;


/*** Methods ***/

	/* ProcessorSimulatorPlugin>>#forceStopOnInterrupt */
static void
forceStopOnInterrupt(void)
{
	if (getInterruptPending()) {
		forceStopRunning();
	}
}


/*	Note: This is hardcoded so it can be run from Squeak.
	The module name is used for validating a module *after*
	it is loaded to check if it does really contain the module
	we're thinking it contains. This is important! */

	/* InterpreterPlugin>>#getModuleName */
EXPORT(const char*)
getModuleName(void)
{
	return moduleName;
}


/*	Answer the value of the primitive64BitPerformanceCounter, if the simulator
	has one.
 */

	/* ProcessorSimulatorPlugin>>#primitive64BitPerformanceCounter */
EXPORT(sqInt)
primitive64BitPerformanceCounter(void)
{
	void *cpu;
	sqInt cpuAlien;
	sqInt maybeErr;
	usqLong perfCounter;

	maybeErr = 0;
	perfCounter = 0;
	cpuAlien = stackValue(methodArgumentCount());
	if (!((cpu = ((void *) (/* startOfData: */
	((longAt((void *)(cpuAlien + BaseHeaderSize))) > 0
		? (cpuAlien + BaseHeaderSize) + BytesPerOop
		: longAt((void *)((cpuAlien + BaseHeaderSize) + BytesPerOop)))))))) {
		return primitiveFailFor(PrimErrBadReceiver);
	}
	if (methodArgumentCount()) {
		if ((methodArgumentCount()) == 1) {
			perfCounter = positive64BitValueOf(stackValue(0));
			if (failed()) {
				return primitiveFailFor(PrimErrBadArgument);
			}
			maybeErr = incrementPerformanceCounter64ofby(cpu, perfCounter);
			if (!maybeErr) {
				return methodReturnReceiver();
			}
		}
		else {
			return primitiveFailFor(PrimErrBadNumArgs);
		}
	}
	else {
		maybeErr = performanceCounter64ofinto(cpu, (&perfCounter));
		if (!maybeErr) {
			return methodReturnValue(positive64BitIntegerFor(perfCounter));
		}
	}
	return primitiveFailForOSError(maybeErr);
}


/*	cpuAlien <CogProcessorAlien> */
/*	<Integer> */
/*	<ByteArray|ShortArray|WordArray|DoubleWordArray> */
/*	Return an Array of the instruction length and its decompilation as a
	string for the instruction at address in memory.
	Prefix the disassembly string with the instruction's address.
 */

	/* ProcessorSimulatorPlugin>>#primitiveDisassembleAt:InMemory: */
EXPORT(sqInt)
primitiveDisassembleAtInMemory(void)
{
	sqInt address;
	void *cpu;
	sqInt cpuAlien;
	sqInt instrLenOrErr;
	char *log;
	long logLen;
	sqInt logObj;
	char *memory;
	sqInt resultObj;

	logLen = 0;
	if (!((isIntegerObject((address = stackValue(1))))
		 && (isWordsOrBytes(stackValue(0))))) {
		return primitiveFailFor(PrimErrBadArgument);
	}
	address = integerValueOf(address);
	memory = firstIndexableField(stackValue(0));
	cpuAlien = stackValue(2);
	if (!((cpu = ((void *) (/* startOfData: */
	((longAt((void *)(cpuAlien + BaseHeaderSize))) > 0
		? (cpuAlien + BaseHeaderSize) + BytesPerOop
		: longAt((void *)((cpuAlien + BaseHeaderSize) + BytesPerOop)))))))) {
		return primitiveFailFor(PrimErrBadReceiver);
	}
	if (address < memoryOffset) {
		return primitiveFailFor(PrimErrBadArgument);
	}
	instrLenOrErr = disassembleForAtInSizePrintAddress(cpu, address, memory - memoryOffset, (byteSizeOf(((sqInt)(sqIntptr_t)(memory) - BaseHeaderSize))) + memoryOffset, 1);
	if (instrLenOrErr < 0) {
		return primitiveFailForOSError(-instrLenOrErr);
	}
	log = getlog((&logLen));
	resultObj = instantiateClassindexableSize(classArray(), 2);
	if (!resultObj) {
		return primitiveFailFor(PrimErrNoMemory);
	}
	
#if SPURVM
	logObj = instantiateClassindexableSize(classString(), logLen);
#else /* SPURVM */
	pushRemappableOop(resultObj);
	logObj = instantiateClassindexableSize(classString(), logLen);
	resultObj = popRemappableOop();
#endif /* SPURVM */
	if (!logObj) {
		return primitiveFailFor(PrimErrNoMemory);
	}
	memcpy(firstIndexableField(logObj), log, logLen);
	storeIntegerofObjectwithValue(0, resultObj, instrLenOrErr);
	storePointerofObjectwithValue(1, resultObj, logObj);
	if (!(failed())) {
		methodReturnValue(resultObj);
	}
	return null;
}


/*	cpuAlien <CogProcessorAlien> */
/*	<Integer> */
/*	<ByteArray|ShortArray|WordArray|DoubleWordArray> */
/*	Return an Array of the instruction length, its decompilation as a string,
	and its address for the instruction at address in memory.
	Don't prefix the disassembly with the instruction's address. */

	/* ProcessorSimulatorPlugin>>#primitiveDisassembleWithAddressAt:InMemory: */
EXPORT(sqInt)
primitiveDisassembleWithAddressAtInMemory(void)
{
	sqInt address;
	void *cpu;
	sqInt cpuAlien;
	sqInt instrLenOrErr;
	char *log;
	long logLen;
	sqInt logObj;
	char *memory;
	sqInt resultObj;

	logLen = 0;
	if (!((isIntegerObject((address = stackValue(1))))
		 && (isWordsOrBytes(stackValue(0))))) {
		return primitiveFailFor(PrimErrBadArgument);
	}
	address = integerValueOf(address);
	memory = firstIndexableField(stackValue(0));
	cpuAlien = stackValue(2);
	if (!((cpu = ((void *) (/* startOfData: */
	((longAt((void *)(cpuAlien + BaseHeaderSize))) > 0
		? (cpuAlien + BaseHeaderSize) + BytesPerOop
		: longAt((void *)((cpuAlien + BaseHeaderSize) + BytesPerOop)))))))) {
		return primitiveFailFor(PrimErrBadReceiver);
	}
	if (address < memoryOffset) {
		return primitiveFailFor(PrimErrBadArgument);
	}
	instrLenOrErr = disassembleForAtInSizePrintAddress(cpu, address, memory - memoryOffset, (byteSizeOf(((sqInt)(sqIntptr_t)(memory) - BaseHeaderSize))) + memoryOffset, 0);
	if (instrLenOrErr < 0) {
		return primitiveFailForOSError(-instrLenOrErr);
	}
	log = getlog((&logLen));
	resultObj = instantiateClassindexableSize(classArray(), 3);
	if (!resultObj) {
		return primitiveFailFor(PrimErrNoMemory);
	}
	
#if SPURVM
	logObj = instantiateClassindexableSize(classString(), logLen);
#else /* SPURVM */
	pushRemappableOop(resultObj);
	logObj = instantiateClassindexableSize(classString(), logLen);
	resultObj = popRemappableOop();
#endif /* SPURVM */
	if (!logObj) {
		return primitiveFailFor(PrimErrNoMemory);
	}
	memcpy(firstIndexableField(logObj), log, logLen);
	storeIntegerofObjectwithValue(0, resultObj, instrLenOrErr);
	storePointerofObjectwithValue(1, resultObj, logObj);
	storeIntegerofObjectwithValue(2, resultObj, address);
	if (!(failed())) {
		methodReturnValue(resultObj);
	}
	return null;
}


/*	cpuAlien <CogProcessorAlien> */
/*	<Integer> */
/*	<Bitmap|ByteArray|WordArray|DoubleWordArray> */
/*	Return an Array of the instruction length and its decompilation as a
	string for the instruction at address in memory.
	Don't prefix the disassembly with the instruction's address. */

	/* ProcessorSimulatorPlugin>>#primitiveDisassembleWithoutAddressAt:InMemory: */
EXPORT(sqInt)
primitiveDisassembleWithoutAddressAtInMemory(void)
{
	sqInt address;
	void *cpu;
	sqInt cpuAlien;
	sqInt instrLenOrErr;
	char *log;
	long logLen;
	sqInt logObj;
	char *memory;
	sqInt resultObj;

	logLen = 0;
	if (!((isIntegerObject((address = stackValue(1))))
		 && (isWordsOrBytes(stackValue(0))))) {
		return primitiveFailFor(PrimErrBadArgument);
	}
	address = integerValueOf(address);
	memory = firstIndexableField(stackValue(0));
	cpuAlien = stackValue(2);
	if (!((cpu = ((void *) (/* startOfData: */
	((longAt((void *)(cpuAlien + BaseHeaderSize))) > 0
		? (cpuAlien + BaseHeaderSize) + BytesPerOop
		: longAt((void *)((cpuAlien + BaseHeaderSize) + BytesPerOop)))))))) {
		return primitiveFailFor(PrimErrBadReceiver);
	}
	if (address < memoryOffset) {
		return primitiveFailFor(PrimErrBadArgument);
	}
	instrLenOrErr = disassembleForAtInSizePrintAddress(cpu, address, memory - memoryOffset, (byteSizeOf(((sqInt)(sqIntptr_t)(memory) - BaseHeaderSize))) + memoryOffset, 0);
	if (instrLenOrErr < 0) {
		return primitiveFailForOSError(-instrLenOrErr);
	}
	log = getlog((&logLen));
	resultObj = instantiateClassindexableSize(classArray(), 2);
	if (!resultObj) {
		return primitiveFailFor(PrimErrNoMemory);
	}
	
#if SPURVM
	logObj = instantiateClassindexableSize(classString(), logLen);
#else /* SPURVM */
	pushRemappableOop(resultObj);
	logObj = instantiateClassindexableSize(classString(), logLen);
	resultObj = popRemappableOop();
#endif /* SPURVM */
	if (!logObj) {
		return primitiveFailFor(PrimErrNoMemory);
	}
	memcpy(firstIndexableField(logObj), log, logLen);
	storeIntegerofObjectwithValue(0, resultObj, instrLenOrErr);
	storePointerofObjectwithValue(1, resultObj, logObj);
	if (!(failed())) {
		methodReturnValue(resultObj);
	}
	return null;
}

	/* ProcessorSimulatorPlugin>>#primitiveErrorAndLog */
EXPORT(sqInt)
primitiveErrorAndLog(void)
{
	char *log;
	long logLen;
	sqInt logObj;
	sqInt resultObj;

	logLen = 0;
	log = getlog((&logLen));
	resultObj = instantiateClassindexableSize(classArray(), 2);
	if (!resultObj) {
		return primitiveFailFor(PrimErrNoMemory);
	}
	storeIntegerofObjectwithValue(0, resultObj, errorAcorn());
	if (logLen > 0) {
		
#if SPURVM
		logObj = instantiateClassindexableSize(classString(), logLen);
#else /* SPURVM */
		pushRemappableOop(resultObj);
		logObj = instantiateClassindexableSize(classString(), logLen);
		resultObj = popRemappableOop();
#endif /* SPURVM */
		if (!logObj) {
			return primitiveFailFor(PrimErrNoMemory);
		}
		memcpy(firstIndexableField(logObj), log, logLen);
		storePointerofObjectwithValue(1, resultObj, logObj);
	}
	methodReturnValue(resultObj);
	return 0;
}


/*	cpuAlien <BochsIA32|X86Alien> */
/*	<Integer> */
/*	<Integer> */
/*	Flush the icache in the requested range */

	/* ProcessorSimulatorPlugin>>#primitiveFlushICacheFrom:To: */
EXPORT(sqInt)
primitiveFlushICacheFromTo(void)
{
	void *cpu;
	sqInt cpuAlien;
	sqInt endAddress;
	sqInt startAddress;

	if (!((isIntegerObject((startAddress = stackValue(1))))
		 && (isIntegerObject((endAddress = stackValue(0)))))) {
		return primitiveFailFor(PrimErrBadArgument);
	}
	startAddress = integerValueOf(startAddress);
	endAddress = integerValueOf(endAddress);
	cpuAlien = stackValue(2);
	if (!((cpu = ((void *) (/* startOfData: */
	((longAt((void *)(cpuAlien + BaseHeaderSize))) > 0
		? (cpuAlien + BaseHeaderSize) + BytesPerOop
		: longAt((void *)((cpuAlien + BaseHeaderSize) + BytesPerOop)))))))) {
		return primitiveFailFor(PrimErrBadReceiver);
	}
	flushICacheFromTo(cpu, startAddress, endAddress);
	if (!(failed())) {
		pop(2);
	}
	return null;
}


/*	Answer an IntegerArray of the processor's integer register state, ending
	with, if these are not otherwise
	included in the register state, the pc and the flags (if the processor has
	flags). This primitive is unnecessary; it exists only to speed up single
	stepping. 
 */

	/* ProcessorSimulatorPlugin>>#primitiveIntegerRegisterState */
EXPORT(sqInt)
primitiveIntegerRegisterState(void)
{
	void *cpu;
	sqInt cpuAlien;
	sqInt dataClass;
	sqInt registerStateVector;

	cpuAlien = stackValue(0);
	if (!((cpu = ((void *) (/* startOfData: */
	((longAt((void *)(cpuAlien + BaseHeaderSize))) > 0
		? (cpuAlien + BaseHeaderSize) + BytesPerOop
		: longAt((void *)((cpuAlien + BaseHeaderSize) + BytesPerOop)))))))) {
		return primitiveFailFor(PrimErrBadReceiver);
	}

	/* The plugin specific include file must define NumIntegerRegisterStateFields */
	dataClass = classWordArray();
	if (dataClass == (nilObject())) {
		return primitiveFailFor(PrimErrUninitialized);
	}
	registerStateVector = instantiateClassindexableSize(dataClass, NumIntegerRegisterStateFields);
	if (!registerStateVector) {
		return primitiveFailFor(PrimErrNoMemory);
	}
	if ((byteSizeOf(registerStateVector)) != (NumIntegerRegisterStateFields * (sizeof(int /* integerRegisterElementType */)))) {
		return primitiveFailFor(PrimErrInternalError);
	}
	storeIntegerRegisterStateOfinto(cpu, firstIndexableField(registerStateVector));
	if (!(failed())) {
		methodReturnValue(registerStateVector);
	}
	return null;
}


/*	Get or set the memory offset. If non-zero the memory offset is one word (4
	or 8 bytes), to marry with the
	SuprMemoryManager simulators discarding of the first word of memory as a
	null pointer trap. */

	/* ProcessorSimulatorPlugin>>#primitiveMemoryOffset */
EXPORT(sqInt)
primitiveMemoryOffset(void)
{
	sqInt offset;
	sqInt previousValue;

	if (!(methodArgumentCount())) {
		return methodReturnInteger(memoryOffset);
	}
	if ((methodArgumentCount()) != 1) {
		return primitiveFailFor(PrimErrBadNumArgs);
	}
	offset = stackValue(0);
	if (!(isIntegerObject(offset))) {
		return primitiveFailFor(PrimErrBadArgument);
	}
	previousValue = memoryOffset;
	memoryOffset = integerValueOf(offset);
	return methodReturnInteger(previousValue);
}

	/* ProcessorSimulatorPlugin>>#primitiveNewCPU */
EXPORT(sqInt)
primitiveNewCPU(void)
{
	void *cpu;

	cpu = newCPU();
	if (!cpu) {
		return primitiveFail();
	}
	methodReturnValue(/* positiveMachineIntegerFor: */
		(BytesPerWord == 8
			? positive64BitIntegerFor(((usqIntptr_t) cpu))
			: positive32BitIntegerFor(((usqIntptr_t) cpu))));
	return 0;
}


/*	Get or set the flag controlling whether when disassembling to print
	instruction bytes on processors with variable length instructions.
 */

	/* ProcessorSimulatorPlugin>>#primitivePrintInstructionBytes */
EXPORT(sqInt)
primitivePrintInstructionBytes(void)
{
	sqInt flag;
	int previousValue;

	if (!(methodArgumentCount())) {
		return methodReturnBool(printInstructionBytes);
	}
	if ((methodArgumentCount()) != 1) {
		return primitiveFailFor(PrimErrBadNumArgs);
	}
	flag = stackValue(0);
	if (!(isBooleanObject(flag))) {
		return primitiveFailFor(PrimErrBadArgument);
	}
	previousValue = printInstructionBytes;
	printInstructionBytes = booleanValueOf(flag);
	return methodReturnBool(previousValue);
}


/*	Answer a DoubleWordArray of the processor's integer register state, ending
	with, if these are not
	otherwise included in the register state, the pc and the flags (if the
	processor has flags), followed
	by the range of double precision floating-point registers in use.
	This primitive is unnecessary; it exists only to speed up single stepping. */

	/* ProcessorSimulatorPlugin>>#primitiveRelevantRegisterState */
EXPORT(sqInt)
primitiveRelevantRegisterState(void)
{
	void *cpu;
	sqInt cpuAlien;
	sqInt dataClass;
	sqInt nfpRegs;
	sqInt registerStateVector;

	cpuAlien = stackValue(0);
	if (!((cpu = ((void *) (/* startOfData: */
	((longAt((void *)(cpuAlien + BaseHeaderSize))) > 0
		? (cpuAlien + BaseHeaderSize) + BytesPerOop
		: longAt((void *)((cpuAlien + BaseHeaderSize) + BytesPerOop)))))))) {
		return primitiveFailFor(PrimErrBadReceiver);
	}

	/* The plugin specific include file must define NumIntegerRegisterStateFields */
	dataClass = classDoubleWordArray();
	if (dataClass == (nilObject())) {
		return primitiveFailFor(PrimErrUninitialized);
	}
	nfpRegs = fpRegHighTide(cpu);
	registerStateVector = instantiateClassindexableSize(dataClass, NumIntegerRegisterStateFields + nfpRegs);
	if (!registerStateVector) {
		return primitiveFailFor(PrimErrNoMemory);
	}
	if ((byteSizeOf(registerStateVector)) != ((NumIntegerRegisterStateFields + nfpRegs) * (sizeof(usqLong)))) {
		return primitiveFailFor(PrimErrInternalError);
	}
	storeRegisterStateOfnfpinto(cpu, nfpRegs, firstIndexableField(registerStateVector));
	if (!(failed())) {
		methodReturnValue(registerStateVector);
	}
	return null;
}

	/* ProcessorSimulatorPlugin>>#primitiveResetCPU */
EXPORT(sqInt)
primitiveResetCPU(void)
{
	void *cpu;
	sqInt cpuAlien;
	sqInt maybeErr;

	cpuAlien = stackValue(0);
	if (!((cpu = ((void *) (/* startOfData: */
	((longAt((void *)(cpuAlien + BaseHeaderSize))) > 0
		? (cpuAlien + BaseHeaderSize) + BytesPerOop
		: longAt((void *)((cpuAlien + BaseHeaderSize) + BytesPerOop)))))))) {
		return primitiveFailFor(PrimErrBadReceiver);
	}
	maybeErr = resetCPU(cpu);
	if (maybeErr) {
		return primitiveFailForOSError(maybeErr);
	}
	if (!(failed())) {
		methodReturnValue(cpuAlien);
	}
	return null;
}


/*	cpuAlien <BochsIA32|X86Alien> */
/*	<Bitmap|ByteArray|WordArray> */
/*	<Integer> */
/*	<Integer> */
/*	<Integer> */
/*	Run the cpu using the first argument as the memory and the following
	arguments defining valid addresses, running until it halts or hits an
	exception. 
 */

	/* ProcessorSimulatorPlugin>>#primitiveRunInMemory:minimumAddress:maximumAddress:readOnlyBelow: */
EXPORT(sqInt)
primitiveRunInMemoryMinAddressMaxAddressReadWrite(void)
{
	void *cpu;
	sqInt cpuAlien;
	sqInt maxAddress;
	sqInt maybeErr;
	char *memory;
	sqInt memorySize;
	sqInt minAddress;
	sqInt minWriteMaxExecAddress;

	if (!((isWordsOrBytes(stackValue(3)))
		 && ((isIntegerObject((minAddress = stackValue(2))))
		 && ((isIntegerObject((maxAddress = stackValue(1))))
		 && (isIntegerObject((minWriteMaxExecAddress = stackValue(0)))))))) {
		return primitiveFailFor(PrimErrBadArgument);
	}
	memory = firstIndexableField(stackValue(3));
	minAddress = integerValueOf(minAddress);
	maxAddress = integerValueOf(maxAddress);
	minWriteMaxExecAddress = integerValueOf(minWriteMaxExecAddress);
	cpuAlien = stackValue(4);
	if (!((cpu = ((void *) (/* startOfData: */
	((longAt((void *)(cpuAlien + BaseHeaderSize))) > 0
		? (cpuAlien + BaseHeaderSize) + BytesPerOop
		: longAt((void *)((cpuAlien + BaseHeaderSize) + BytesPerOop)))))))) {
		return primitiveFailFor(PrimErrBadReceiver);
	}
	if ((minAddress < memoryOffset)
	 || ((maxAddress < memoryOffset)
	 || (minWriteMaxExecAddress < memoryOffset))) {
		return primitiveFailFor(PrimErrBadArgument);
	}

	/* Add forceStopOnInterrupt to the interrupt check chain.  It is our responsibility to
	   chain calls, hence we remember any previous client in prevInterruptCheckChain. */
	prevInterruptCheckChain = setInterruptCheckChain(forceStopOnInterrupt);
	if (prevInterruptCheckChain == forceStopOnInterrupt) {
		prevInterruptCheckChain = 0;
	}
	memorySize = byteSizeOf(((sqInt)(sqIntptr_t)(memory) - BaseHeaderSize));
	maybeErr = runCPUInSizeMinAddressReadWrite(cpu, memory - memoryOffset, (((memorySize + memoryOffset) < maxAddress) ? (memorySize + memoryOffset) : maxAddress), minAddress, minWriteMaxExecAddress);
	setInterruptCheckChain(prevInterruptCheckChain);
	if (maybeErr) {
		return primitiveFailForOSError(maybeErr);
	}
	if (!(failed())) {
		methodReturnValue(cpuAlien);
	}
	return null;
}


/*	cpuAlien <BochsIA32|X86Alien> */
/*	<Bitmap|ByteArray|WordArray> */
/*	<Integer> */
/*	<Integer> */
/*	Run the cpu using the first argument as the memory and the following
	arguments defining valid addresses, running until it halts or hits an
	exception. 
 */

	/* ProcessorSimulatorPlugin>>#primitiveRunInMemory:minimumAddress:readOnlyBelow: */
EXPORT(sqInt)
primitiveRunInMemoryMinimumAddressReadWrite(void)
{
	void *cpu;
	sqInt cpuAlien;
	sqInt maybeErr;
	char *memory;
	sqInt minAddress;
	sqInt minWriteMaxExecAddress;

	if (!((isWordsOrBytes(stackValue(2)))
		 && ((isIntegerObject((minAddress = stackValue(1))))
		 && (isIntegerObject((minWriteMaxExecAddress = stackValue(0))))))) {
		return primitiveFailFor(PrimErrBadArgument);
	}
	memory = firstIndexableField(stackValue(2));
	minAddress = integerValueOf(minAddress);
	minWriteMaxExecAddress = integerValueOf(minWriteMaxExecAddress);
	cpuAlien = stackValue(3);
	if (!((cpu = ((void *) (/* startOfData: */
	((longAt((void *)(cpuAlien + BaseHeaderSize))) > 0
		? (cpuAlien + BaseHeaderSize) + BytesPerOop
		: longAt((void *)((cpuAlien + BaseHeaderSize) + BytesPerOop)))))))) {
		return primitiveFailFor(PrimErrBadReceiver);
	}
	if ((minAddress < memoryOffset)
	 || (minWriteMaxExecAddress < memoryOffset)) {
		return primitiveFailFor(PrimErrBadArgument);
	}
	prevInterruptCheckChain = setInterruptCheckChain(forceStopOnInterrupt);
	if (prevInterruptCheckChain == forceStopOnInterrupt) {
		prevInterruptCheckChain = 0;
	}
	maybeErr = runCPUInSizeMinAddressReadWrite(cpu, memory - memoryOffset, (byteSizeOf(((sqInt)(sqIntptr_t)(memory) - BaseHeaderSize))) + memoryOffset, minAddress, minWriteMaxExecAddress);
	setInterruptCheckChain(prevInterruptCheckChain);
	if (maybeErr) {
		return primitiveFailForOSError(maybeErr);
	}
	if (!(failed())) {
		methodReturnValue(cpuAlien);
	}
	return null;
}


/*	cpuAlien <ProcessorSimulatorAlien> */
/*	<BitsObject> */
/*	<Integer> */
/*	<Integer> */
/*	<Integer> */
/*	Run the cpu using the first argument as the memory and the following
	arguments defining valid addresses, running until it halts or hits an
	exception. 
 */

	/* ProcessorSimulatorPlugin>>#primitiveRunInMemory:offsetBy:minimumAddress:readOnlyBelow: */
EXPORT(sqInt)
primitiveRunInMemoryOffsetMinimumAddressReadWrite(void)
{
	void *cpu;
	sqInt cpuAlien;
	sqInt maybeErr;
	char *memory;
	sqInt minAddress;
	sqInt minWriteMaxExecAddress;
	sqInt offset;

	if (!((isWordsOrBytes(stackValue(3)))
		 && ((isIntegerObject((offset = stackValue(2))))
		 && ((isIntegerObject((minAddress = stackValue(1))))
		 && (isIntegerObject((minWriteMaxExecAddress = stackValue(0)))))))) {
		return primitiveFailFor(PrimErrBadArgument);
	}
	memory = firstIndexableField(stackValue(3));
	offset = integerValueOf(offset);
	minAddress = integerValueOf(minAddress);
	minWriteMaxExecAddress = integerValueOf(minWriteMaxExecAddress);
	cpuAlien = stackValue(4);
	if (!((cpu = ((void *) (/* startOfData: */
	((longAt((void *)(cpuAlien + BaseHeaderSize))) > 0
		? (cpuAlien + BaseHeaderSize) + BytesPerOop
		: longAt((void *)((cpuAlien + BaseHeaderSize) + BytesPerOop)))))))) {
		return primitiveFailFor(PrimErrBadReceiver);
	}
	if ((minAddress < memoryOffset)
	 || (minWriteMaxExecAddress < memoryOffset)) {
		return primitiveFailFor(PrimErrBadArgument);
	}
	prevInterruptCheckChain = setInterruptCheckChain(forceStopOnInterrupt);
	if (prevInterruptCheckChain == forceStopOnInterrupt) {
		prevInterruptCheckChain = 0;
	}
	maybeErr = runCPUInSizeMinAddressReadWrite(cpu, ((((char *) memory)) - memoryOffset) + offset, ((byteSizeOf(((sqInt)(sqIntptr_t)(memory) - BaseHeaderSize))) + memoryOffset) - offset, minAddress, minWriteMaxExecAddress);
	setInterruptCheckChain(prevInterruptCheckChain);
	if (maybeErr) {
		return primitiveFailForOSError(maybeErr);
	}
	if (!(failed())) {
		methodReturnValue(cpuAlien);
	}
	return null;
}


/*	cpuAlien <BochsIA32|X86Alien> */
/*	<Bitmap|ByteArray|WordArray> */
/*	<Integer> */
/*	<Integer> */
/*	<Integer> */
/*	Single-step the cpu using the first argument as the memory and the
	following arguments defining valid addresses.
 */

	/* ProcessorSimulatorPlugin>>#primitiveSingleStepInMemory:minimumAddress:maximumAddress:readOnlyBelow: */
EXPORT(sqInt)
primitiveSingleStepInMemoryMinAddressMaxAddressReadWrite(void)
{
	void *cpu;
	sqInt cpuAlien;
	sqInt maxAddress;
	sqInt maybeErr;
	char *memory;
	sqInt memorySize;
	sqInt minAddress;
	sqInt minWriteMaxExecAddress;

	if (!((isWordsOrBytes(stackValue(3)))
		 && ((isIntegerObject((minAddress = stackValue(2))))
		 && ((isIntegerObject((maxAddress = stackValue(1))))
		 && (isIntegerObject((minWriteMaxExecAddress = stackValue(0)))))))) {
		return primitiveFailFor(PrimErrBadArgument);
	}
	memory = firstIndexableField(stackValue(3));
	minAddress = integerValueOf(minAddress);
	maxAddress = integerValueOf(maxAddress);
	minWriteMaxExecAddress = integerValueOf(minWriteMaxExecAddress);
	cpuAlien = stackValue(4);
	if (!((cpu = ((void *) (/* startOfData: */
	((longAt((void *)(cpuAlien + BaseHeaderSize))) > 0
		? (cpuAlien + BaseHeaderSize) + BytesPerOop
		: longAt((void *)((cpuAlien + BaseHeaderSize) + BytesPerOop)))))))) {
		return primitiveFailFor(PrimErrBadReceiver);
	}
	if ((minAddress < memoryOffset)
	 || ((maxAddress < memoryOffset)
	 || (minWriteMaxExecAddress < memoryOffset))) {
		return primitiveFailFor(PrimErrBadArgument);
	}
	memorySize = byteSizeOf(((sqInt)(sqIntptr_t)(memory) - BaseHeaderSize));
	maybeErr = singleStepCPUInSizeMinAddressReadWrite(cpu, memory - memoryOffset, (((memorySize + memoryOffset) < maxAddress) ? (memorySize + memoryOffset) : maxAddress), minAddress, minWriteMaxExecAddress);
	if (maybeErr) {
		return primitiveFailForOSError(maybeErr);
	}
	if (!(failed())) {
		methodReturnValue(cpuAlien);
	}
	return null;
}


/*	cpuAlien <BochsIA32|X86Alien> */
/*	<Bitmap|ByteArray|WordArray> */
/*	<Integer> */
/*	<Integer> */
/*	Single-step the cpu using the first argument as the memory and the
	following arguments defining valid addresses.
 */

	/* ProcessorSimulatorPlugin>>#primitiveSingleStepInMemory:minimumAddress:readOnlyBelow: */
EXPORT(sqInt)
primitiveSingleStepInMemoryMinimumAddressReadWrite(void)
{
	void *cpu;
	sqInt cpuAlien;
	sqInt maybeErr;
	char *memory;
	sqInt minAddress;
	sqInt minWriteMaxExecAddress;

	if (!((isWordsOrBytes(stackValue(2)))
		 && ((isIntegerObject((minAddress = stackValue(1))))
		 && (isIntegerObject((minWriteMaxExecAddress = stackValue(0))))))) {
		return primitiveFailFor(PrimErrBadArgument);
	}
	memory = firstIndexableField(stackValue(2));
	minAddress = integerValueOf(minAddress);
	minWriteMaxExecAddress = integerValueOf(minWriteMaxExecAddress);
	cpuAlien = stackValue(3);
	if (!((cpu = ((void *) (/* startOfData: */
	((longAt((void *)(cpuAlien + BaseHeaderSize))) > 0
		? (cpuAlien + BaseHeaderSize) + BytesPerOop
		: longAt((void *)((cpuAlien + BaseHeaderSize) + BytesPerOop)))))))) {
		return primitiveFailFor(PrimErrBadReceiver);
	}
	if ((minAddress < memoryOffset)
	 || (minWriteMaxExecAddress < memoryOffset)) {
		return primitiveFailFor(PrimErrBadArgument);
	}
	maybeErr = singleStepCPUInSizeMinAddressReadWrite(cpu, memory - memoryOffset, (byteSizeOf(((sqInt)(sqIntptr_t)(memory) - BaseHeaderSize))) + memoryOffset, minAddress, minWriteMaxExecAddress);
	if (maybeErr) {
		return primitiveFailForOSError(maybeErr);
	}
	if (!(failed())) {
		methodReturnValue(cpuAlien);
	}
	return null;
}


/*	cpuAlien <BochsIA32|X86Alien> */
/*	<Bitmap|ByteArray|WordArray> */
/*	<Integer> */
/*	<Integer> */
/*	<Integer> */
/*	Single-step the cpu using the first argument as the memory and the
	following arguments defining valid addresses.
 */

	/* ProcessorSimulatorPlugin>>#primitiveSingleStepInMemory:offsetBy:minimumAddress:readOnlyBelow: */
EXPORT(sqInt)
primitiveSingleStepInMemoryOffsetMinimumAddressReadWrite(void)
{
	void *cpu;
	sqInt cpuAlien;
	sqInt maybeErr;
	char *memory;
	sqInt minAddress;
	sqInt minWriteMaxExecAddress;
	sqInt offset;

	if (!((isWordsOrBytes(stackValue(3)))
		 && ((isIntegerObject((offset = stackValue(2))))
		 && ((isIntegerObject((minAddress = stackValue(1))))
		 && (isIntegerObject((minWriteMaxExecAddress = stackValue(0)))))))) {
		return primitiveFailFor(PrimErrBadArgument);
	}
	memory = firstIndexableField(stackValue(3));
	offset = integerValueOf(offset);
	minAddress = integerValueOf(minAddress);
	minWriteMaxExecAddress = integerValueOf(minWriteMaxExecAddress);
	cpuAlien = stackValue(4);
	if (!((cpu = ((void *) (/* startOfData: */
	((longAt((void *)(cpuAlien + BaseHeaderSize))) > 0
		? (cpuAlien + BaseHeaderSize) + BytesPerOop
		: longAt((void *)((cpuAlien + BaseHeaderSize) + BytesPerOop)))))))) {
		return primitiveFailFor(PrimErrBadReceiver);
	}
	if ((minAddress < memoryOffset)
	 || (minWriteMaxExecAddress < memoryOffset)) {
		return primitiveFailFor(PrimErrBadArgument);
	}
	maybeErr = singleStepCPUInSizeMinAddressReadWrite(cpu, ((((char *) memory)) - memoryOffset) + offset, ((byteSizeOf(((sqInt)(sqIntptr_t)(memory) - BaseHeaderSize))) - offset) + memoryOffset, minAddress, minWriteMaxExecAddress);
	if (maybeErr) {
		return primitiveFailForOSError(maybeErr);
	}
	if (!(failed())) {
		methodReturnValue(cpuAlien);
	}
	return null;
}


/*	Note: This is coded so that it can be run in Squeak. */

	/* InterpreterPlugin>>#setInterpreter: */
EXPORT(sqInt)
setInterpreter(struct VirtualMachine *anInterpreter)
{
	sqInt ok;

	interpreterProxy = anInterpreter;

	/* This may seem tautological, but in a real plugin it checks that the VM provides
	   the version the plugin was compiled against which is the version the plugin expects. */
	ok = ((interpreterProxy->majorVersion()) == (VM_PROXY_MAJOR))
		 && ((interpreterProxy->minorVersion()) >= (VM_PROXY_MINOR));
	if (ok) {
		
#if !defined(SQUEAK_BUILTIN_PLUGIN)
		booleanValueOf = interpreterProxy->booleanValueOf;
		byteSizeOf = interpreterProxy->byteSizeOf;
		classArray = interpreterProxy->classArray;
#if VM_PROXY_MAJOR > 1 || (VM_PROXY_MAJOR == 1 && VM_PROXY_MINOR >= 16)
		classDoubleWordArray = interpreterProxy->classDoubleWordArray;
#else
#if !defined(classDoubleWordArray)
		classDoubleWordArray = 0;
#endif
#endif
		classString = interpreterProxy->classString;
#if VM_PROXY_MAJOR > 1 || (VM_PROXY_MAJOR == 1 && VM_PROXY_MINOR >= 16)
		classWordArray = interpreterProxy->classWordArray;
#else
#if !defined(classWordArray)
		classWordArray = 0;
#endif
#endif
		failed = interpreterProxy->failed;
		firstIndexableField = interpreterProxy->firstIndexableField;
		getInterruptPending = interpreterProxy->getInterruptPending;
		instantiateClassindexableSize = interpreterProxy->instantiateClassindexableSize;
#if !defined(integerValueOf)
		integerValueOf = interpreterProxy->integerValueOf;
#endif
#if VM_PROXY_MAJOR > 1 || (VM_PROXY_MAJOR == 1 && VM_PROXY_MINOR >= 15)
		isBooleanObject = interpreterProxy->isBooleanObject;
#else
#if !defined(isBooleanObject)
		isBooleanObject = 0;
#endif
#endif
#if !defined(isIntegerObject)
		isIntegerObject = interpreterProxy->isIntegerObject;
#endif
		isWordsOrBytes = interpreterProxy->isWordsOrBytes;
		methodArgumentCount = interpreterProxy->methodArgumentCount;
		methodReturnBool = interpreterProxy->methodReturnBool;
		methodReturnInteger = interpreterProxy->methodReturnInteger;
		methodReturnReceiver = interpreterProxy->methodReturnReceiver;
		methodReturnValue = interpreterProxy->methodReturnValue;
		nilObject = interpreterProxy->nilObject;
		pop = interpreterProxy->pop;
		popRemappableOop = interpreterProxy->popRemappableOop;
		positive32BitIntegerFor = interpreterProxy->positive32BitIntegerFor;
		positive64BitIntegerFor = interpreterProxy->positive64BitIntegerFor;
		positive64BitValueOf = interpreterProxy->positive64BitValueOf;
		primitiveFail = interpreterProxy->primitiveFail;
		primitiveFailFor = interpreterProxy->primitiveFailFor;
#if VM_PROXY_MAJOR > 1 || (VM_PROXY_MAJOR == 1 && VM_PROXY_MINOR >= 14)
		primitiveFailForOSError = interpreterProxy->primitiveFailForOSError;
#else
#if !defined(primitiveFailForOSError)
		primitiveFailForOSError = 0;
#endif
#endif
		pushRemappableOop = interpreterProxy->pushRemappableOop;
		setInterruptCheckChain = interpreterProxy->setInterruptCheckChain;
		stackValue = interpreterProxy->stackValue;
		storeIntegerofObjectwithValue = interpreterProxy->storeIntegerofObjectwithValue;
		storePointerofObjectwithValue = interpreterProxy->storePointerofObjectwithValue;
#endif /* !defined(SQUEAK_BUILTIN_PLUGIN) */
	}
	return ok;
}

/*** Exports ***/

#ifdef SQUEAK_BUILTIN_PLUGIN

static char _m[] = "BochsIA32Plugin";
void* BochsIA32Plugin_exports[][3] = {
	{(void*)_m, "getModuleName", (void*)getModuleName},
	{(void*)_m, "primitive64BitPerformanceCounter\000\000\000", (void*)primitive64BitPerformanceCounter},
	{(void*)_m, "primitiveDisassembleAtInMemory\000\001\000", (void*)primitiveDisassembleAtInMemory},
	{(void*)_m, "primitiveDisassembleWithAddressAtInMemory\000\001\000", (void*)primitiveDisassembleWithAddressAtInMemory},
	{(void*)_m, "primitiveDisassembleWithoutAddressAtInMemory\000\001\000", (void*)primitiveDisassembleWithoutAddressAtInMemory},
	{(void*)_m, "primitiveErrorAndLog\000\377\000", (void*)primitiveErrorAndLog},
	{(void*)_m, "primitiveFlushICacheFromTo\000\000\000", (void*)primitiveFlushICacheFromTo},
	{(void*)_m, "primitiveIntegerRegisterState\000\000\000", (void*)primitiveIntegerRegisterState},
	{(void*)_m, "primitiveMemoryOffset\000\000\001", (void*)primitiveMemoryOffset},
	{(void*)_m, "primitiveNewCPU\000\377\000", (void*)primitiveNewCPU},
	{(void*)_m, "primitivePrintInstructionBytes\000\000\001", (void*)primitivePrintInstructionBytes},
	{(void*)_m, "primitiveRelevantRegisterState\000\000\000", (void*)primitiveRelevantRegisterState},
	{(void*)_m, "primitiveResetCPU\000\000\000", (void*)primitiveResetCPU},
	{(void*)_m, "primitiveRunInMemoryMinAddressMaxAddressReadWrite\000\001\000", (void*)primitiveRunInMemoryMinAddressMaxAddressReadWrite},
	{(void*)_m, "primitiveRunInMemoryMinimumAddressReadWrite\000\001\000", (void*)primitiveRunInMemoryMinimumAddressReadWrite},
	{(void*)_m, "primitiveRunInMemoryOffsetMinimumAddressReadWrite\000\001\000", (void*)primitiveRunInMemoryOffsetMinimumAddressReadWrite},
	{(void*)_m, "primitiveSingleStepInMemoryMinAddressMaxAddressReadWrite\000\001\000", (void*)primitiveSingleStepInMemoryMinAddressMaxAddressReadWrite},
	{(void*)_m, "primitiveSingleStepInMemoryMinimumAddressReadWrite\000\001\000", (void*)primitiveSingleStepInMemoryMinimumAddressReadWrite},
	{(void*)_m, "primitiveSingleStepInMemoryOffsetMinimumAddressReadWrite\000\001\000", (void*)primitiveSingleStepInMemoryOffsetMinimumAddressReadWrite},
	{(void*)_m, "setInterpreter", (void*)setInterpreter},
	{NULL, NULL, NULL}
};

#else // ifdef SQ_BUILTIN_PLUGIN

#if SPURVM
EXPORT(signed short) primitive64BitPerformanceCounterMetadata = 0;
EXPORT(signed short) primitiveDisassembleAtInMemoryMetadata = 0x100;
EXPORT(signed short) primitiveDisassembleWithAddressAtInMemoryMetadata = 0x100;
EXPORT(signed short) primitiveDisassembleWithoutAddressAtInMemoryMetadata = 0x100;
EXPORT(signed short) primitiveFlushICacheFromToMetadata = 0;
EXPORT(signed short) primitiveIntegerRegisterStateMetadata = 0;
EXPORT(signed short) primitiveMemoryOffsetMetadata = 1;
EXPORT(signed short) primitivePrintInstructionBytesMetadata = 1;
EXPORT(signed short) primitiveRelevantRegisterStateMetadata = 0;
EXPORT(signed short) primitiveResetCPUMetadata = 0;
EXPORT(signed short) primitiveRunInMemoryMinAddressMaxAddressReadWriteMetadata = 0x100;
EXPORT(signed short) primitiveRunInMemoryMinimumAddressReadWriteMetadata = 0x100;
EXPORT(signed short) primitiveRunInMemoryOffsetMinimumAddressReadWriteMetadata = 0x100;
EXPORT(signed short) primitiveSingleStepInMemoryMinAddressMaxAddressReadWriteMetadata = 0x100;
EXPORT(signed short) primitiveSingleStepInMemoryMinimumAddressReadWriteMetadata = 0x100;
EXPORT(signed short) primitiveSingleStepInMemoryOffsetMinimumAddressReadWriteMetadata = 0x100;
#endif // SPURVM

#endif // ifdef SQ_BUILTIN_PLUGIN
