#!/bin/bash -e
trap 'exit 2' HUP INT PIPE TERM
for d in *.spur *.v3; do
	if test -d "$d"; then
		(cd ./$d;./mvm)
	else
		echo no $d directory found
	fi
done
echo no news is good news...
grep -w error: *.spur/LOG* *.v3/LOG*
