#define b3dxInitialize            b3dMetalInitialize
#define b3dxShutdown              b3dMetalShutdown

#define b3dxAllocateTexture       b3dMetalAllocateTexture
#define b3dxDestroyTexture        b3dMetalDestroyTexture
#define b3dxActualTextureDepth    b3dMetalActualTextureDepth
#define b3dxTextureColorMasks     b3dMetalTextureColorMasks
#define b3dxUploadTexture         b3dMetalUploadTexture
#define b3dxTextureByteSex        b3dMetalTextureByteSex
#define b3dxTextureSurfaceHandle b3dMetalTextureSurfaceHandle
#define b3dxCompositeTexture      b3dMetalCompositeTexture

#define b3dxCreateRendererFlags   b3dMetalCreateRendererFlags
#define b3dxDestroyRenderer        b3dMetalDestroyRenderer
#define b3dxIsOverlayRenderer     b3dMetalIsOverlayRenderer
#define b3dxGetRendererSurfaceHandle b3dMetalGetRendererSurfaceHandle
#define b3dxGetRendererSurfaceWidth b3dMetalGetRendererSurfaceWidth
#define b3dxGetRendererSurfaceHeight b3dMetalGetRendererSurfaceHeight
#define b3dxGetRendererSurfaceDepth b3dMetalGetRendererSurfaceDepth
#define b3dxGetRendererColorMasks b3dMetalGetRendererColorMasks
#define b3dxSetBufferRect           b3dMetalSetBufferRect

#define b3dxSetViewport          b3dMetalSetViewport
#define b3dxClearDepthBuffer     b3dMetalClearDepthBuffer
#define b3dxClearViewport        b3dMetalClearViewport
#define b3dxRenderVertexBuffer   b3dMetalRenderVertexBuffer
#define b3dxSetTransform         b3dMetalSetTransform
#define b3dxDisableLights        b3dMetalDisableLights
#define b3dxLoadLight            b3dMetalLoadLight
#define b3dxLoadMaterial         b3dMetalLoadMaterial
#define b3dxFlushRenderer        b3dMetalFlushRenderer
#define b3dxFinishRenderer       b3dMetalFinishRenderer
#define b3dxSwapRendererBuffers  b3dMetalSwapRendererBuffers
#define b3dxGetIntProperty       b3dMetalGetIntProperty
#define b3dxSetIntProperty       b3dMetalSetIntProperty
#define b3dxGetIntPropertyOS     b3dMetalGetIntPropertyOS
#define b3dxSetIntPropertyOS     b3dMetalSetIntPropertyOS
#define b3dxSetVerboseLevel      b3dMetalSetVerboseLevel
#define b3dxSetFog               b3dMetalSetFog