##############################################################################
# Makefile for Mac OS X Stack Spur Glue Cocoa VM using clang and gnu make 3.81
# Do make init to allow make -n to function.
#

VMSRCDIR:= ../../nsspurstacksrc/vm
COGDEFS:=-DEnforceAccessControl=0

include ../common/Makefile.app.newspeak
