#!/bin/bash
# Build a "complete" Mac VM consisting of CoreVM/CoreMTVM + Plugins.
# By default build the Deployment configuration into $APP (Squeak.app)
IFS='	
'
BUILD_CONFIGURATION=Deployment
NSD_BUILD_CONFIGURATION=Deployment
XCD_BUILD_CONFIGURATION=Release
APP=Squeak.app
VMAPP=".app"
DEST="Squeak"
VMXCP=CoreVM
SFP=SqueakFFIPrims
KEEP=

USAGE="usage: `basename $0` -[admskh?]"

while getopts 'admskh?' opt $@; do
	case $opt in
	a)		BUILD_CONFIGURATION=Assert
			NSD_BUILD_CONFIGURATION=Development
			XCD_BUILD_CONFIGURATION=Debug
			DEST=Assert;;
	d)		BUILD_CONFIGURATION=Development
			NSD_BUILD_CONFIGURATION=Development
			XCD_BUILD_CONFIGURATION=Debug
			DEST=Debug;;
	m)		VMAPP="MT.app";
			VMXCP=CoreMTVM;
			SFP=SqueakMTFFIPrims;;
	s)		BUILD_CONFIGURATION=DeploymentSymbols
			DEST=Fast;;
	k)		KEEP=1;;
	h|\?|*)	echo $USAGE
			echo '	build the vm (defaults to a Deployment version)'
			echo '  -a: compile Assert configuration in Assert.app for assert checks'
			echo '  -d: compile Development configuration in Debug.app for debugging'
			echo '  -m: compile the multi-threaded version of the target, e.g. FastMT.app instead of Fast.app'
			echo '  -s: compile DeploymentSymbols configuration in Fast.app for partial debugging'
			echo "  -k: keep (do not delete) the existing $APP prior to the build"
			echo '	-h: display this help'
			exit 0;;
	esac
done

DEST="$DEST$VMAPP"
if [ -z "$DEVELOPER_SDK_DIR" ]; then
	DEVELOPER_SDK_DIR=/Developer/SDKs
fi
test -d "$DEVELOPER_SDK_DIR" || echo '$DEVELOPER_SDK_DIR' "$DEVELOPER_SDK_DIR" does not exist \(needed by $SFP project\)
export DEVELOPER_SDK_DIR
if [ ! -d "$DEVELOPER_SDK_DIR/MacOSX10.5.sdk" ]; then
	if [ -d "$DEVELOPER_SDK_DIR/MacOSX10.4u.sdk" ]; then
		export SDKROOT="$DEVELOPER_SDK_DIR/MacOSX10.4u.sdk"
	fi
fi

test "$KEEP" = 1 || rm -rf "$DEST"/* "$DEST"/.??*

# Build CoreVM/CoreMTVM using xcode
echo
echo $VMXCP xcodebuild -project $VMXCP.xcodeproj -configuration $BUILD_CONFIGURATION
xcodebuild -project $VMXCP.xcodeproj -configuration $BUILD_CONFIGURATION
if [ -d "$DEST" ]; then
	mv build/$BUILD_CONFIGURATION/$APP/* "$DEST"
else
	mv build/$BUILD_CONFIGURATION/$APP "$DEST"
fi
../scripts/versionInfoPlist ../platforms CoreVM.plist "$DEST/Contents/Info.plist"

# Build the Float plugin
echo
echo FloatMathPlugin xcodebuild -project FloatMathPlugin/FloatMathPlugin.xcodeproj -configuration Release
xcodebuild -project FloatMathPlugin/FloatMathPlugin.xcodeproj -configuration Release
rm -rf "$DEST/Contents/Resources/FloatMathPlugin.bundle"
cp -R FloatMathPlugin/build/Release/FloatMathPlugin.bundle "$DEST/Contents/Resources"

# Build the FloatArray plugin
echo
echo FloatArrayPlugin xcodebuild -project FloatArrayPlugin/FloatArrayPlugin.xcodeproj -configuration Release
xcodebuild -project FloatArrayPlugin/FloatArrayPlugin.xcodeproj -configuration Release
rm -rf "$DEST/Contents/Resources/FloatArrayPlugin.bundle"
cp -R FloatArrayPlugin/build/Release/FloatArrayPlugin.bundle "$DEST/Contents/Resources"

# Build the Croquet plugin
echo
echo CroquetPlugin xcodebuild -project CroquetPlugin/CroquetPlugin.xcodeproj -configuration Release
xcodebuild -project CroquetPlugin/CroquetPlugin.xcodeproj -configuration Release
rm -rf "$DEST/Contents/Resources/CroquetPlugin.bundle"
cp -R CroquetPlugin/build/Release/CroquetPlugin.bundle "$DEST/Contents/Resources"

#Build the mpeg3 plugin
echo
echo Mpeg3Plugin xcodebuild -project Mpeg3Plugin/Mpeg3Plugin.xcodeproj -configuration $NSD_BUILD_CONFIGURATION
xcodebuild -project Mpeg3Plugin/Mpeg3Plugin.xcodeproj -configuration $NSD_BUILD_CONFIGURATION
cp -R Mpeg3Plugin/build/Release/Mpeg3Plugin.bundle mpeg3.app/Contents/Resources

# Build the FFI plugin (New as of 27 March 2008)
echo
echo SqueakFFIPlugin xcodebuild -project $SFP/SqueakFFI.xcodeproj -configuration $NSD_BUILD_CONFIGURATION
xcodebuild -project $SFP/SqueakFFI.xcodeproj -configuration $NSD_BUILD_CONFIGURATION
rm -rf "$DEST/Contents/Resources/SqueakFFIPrims.bundle"
cp -R $SFP/build/$NSD_BUILD_CONFIGURATION/SqueakFFIPrims.bundle "$DEST/Contents/Resources"

# Build the SSL plugin (New as of 25 March 2013)
echo
echo SqueakSSL xcodebuild -project SqueakSSL/SqueakSSL.xcodeproj -configuration $XCD_BUILD_CONFIGURATION
xcodebuild -project SqueakSSL/SqueakSSL.xcodeproj -configuration $XCD_BUILD_CONFIGURATION
rm -rf "$DEST/Contents/Resources/SqueakSSL.bundle"
cp -R SqueakSSL/build/$XCD_BUILD_CONFIGURATION/SqueakSSL.bundle "$DEST/Contents/Resources"

# Build the BochsIA32Plugin
# N.B. To build the plugin you also have to build the Bochs libraries in
# ../processors/IA32/bochs.  cd ../processors/IA32/bochs. Run conf.COG & makeem.
echo BochsIA32Plugin xcodebuild -configuration $XCD_BUILD_CONFIGURATION -project BochsIA32Plugin/BochsIA32Plugin.xcodeproj
xcodebuild -configuration $XCD_BUILD_CONFIGURATION -project BochsIA32Plugin/BochsIA32Plugin.xcodeproj
rm -rf "$DEST/Contents/Resources/BochsIA32Plugin.bundle"
cp -R BochsIA32Plugin/build/$XCD_BUILD_CONFIGURATION/BochsIA32Plugin.bundle "$DEST/Contents/Resources"

# Build the UnixOSProcessPlugin
echo UnixOSProcessPlugin xcodebuild -configuration $XCD_BUILD_CONFIGURATION -project UnixOSProcessPlugin/UnixOSProcessPlugin.xcodeproj
xcodebuild -configuration $XCD_BUILD_CONFIGURATION -project UnixOSProcessPlugin/UnixOSProcessPlugin.xcodeproj
rm -rf "$DEST/Contents/Resources/UnixOSProcessPlugin.bundle"
cp -R UnixOSProcessPlugin/build/$XCD_BUILD_CONFIGURATION/UnixOSProcessPlugin.bundle "$DEST/Contents/Resources"

# Clean out any .svn directories (result of copying) in the VM
find "$DEST" -name .svn -exec rm -rf {} \;
