#############################################################################
# Compilation rules for Mac OS X
#
# See http://make.mad-scientist.net/papers/advanced-auto-dependency-generation
# for an explanation of the dependency management scheme.

# /usr/bin/clang, a.k.a. /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CC := clang
CXX := clang++
LD := clang
LDCXX := clang++ # For linking c++ bundles
ifeq ($(CXXVERFLAGS),)
CXXVERFLAGS:=-std=c++14 -stdlib=libc++
endif

include ../common/Makefile.flags

DEPFLAGS = -MMD -MT '$$(OBJDIR)/$(*F).o' -MF deps/$(*F).d
ALLFLAGS = $(DEPFLAGS) $(WARNINGS) $(CFLAGS)

$(OBJDIR)/%.o: %.c deps/%.d $(MAKEFILE)
	$(CC) -x c $(ALLFLAGS) $(INCLUDES) -c $< -o $@

$(OBJDIR)/%.o: %.m deps/%.d $(MAKEFILE)
	$(CC) -x objective-c $(OBJC_CODE_MODEL) $(ALLFLAGS) $(INCLUDES) -c $< -o $@

$(OBJDIR)/%.o: %.cpp deps/%.d $(MAKEFILE)
	$(CXX) $(CXXVERFLAGS) $(ALLFLAGS) $(INCLUDES) -c $< -o $@

$(OBJDIR)/%.o: %.mm deps/%.d $(MAKEFILE)
	$(CXX) $(CXXVERFLAGS) $(OBJC_CODE_MODEL) $(ALLFLAGS) $(INCLUDES) -c $< -o $@

deps/%.d: ;

.PRECIOUS: deps/%.d $(OBJDIR)/%.air $(OBJDIR)/%.metallib

-include $(patsubst %,deps/%.d,$(notdir $(basename $(VMSRC) $(LIBSRC))))
