#!/bin/bash -e
IFS="
	"
trap 'exit 2' HUP INT PIPE TERM
REV=`grep 'GitRawRevisionString.*Rev:' "\`dirname $0\`/../platforms/Cross/vm/sqSCCSVersion.h \
	| sed 's/^.*Rev: \([0-9][0-9]*\).* $";/\1/'`
TAG=`date +%y.%U.`$REV
set -- Newspeak\ Virtual\ Machine	Newspeak\ Spur\ Virtual\ Machine
for td in newspeak.cog.spur; do
	d=$td/installer
	PRODUCT=$1-$TAG.dmg
	if test -d "$d"; then
		(cd ./$d;make)
		test -f $d/$PRODUCT && mv $d/$PRODUCT ../products
	else
		echo no $d directory found
	fi
	shift
done
