#!/usr/bin/env bash
set -e
# Spur VM with VM profiler and itimer heartbeat
INSTALLDIR=nsnaccogspur64linux
# Some gcc versions create a broken VM using -O2
OPT="-g -O2 -DNDEBUG -DDEBUGVM=0"

if [ $# -ge 1 ]; then
	case "$1" in
	-*)	;;
	*)	INSTALLDIR="$1"; shift
	esac
fi

if ../../../../scripts/checkSCCSversion ; then exit 1; fi
echo -n "clean? "
read a
case $a in
n|no|N|NO)	echo "ok but this isn't safe!!";;
*)			rm -f config.h; test -f Makefile && make reallyclean
esac
test -f plugins.int || (test -f ../plugins.int && cp -p ../plugins.int . || cp -p ../../plugins.int .)
test -f plugins.ext || (test -f ../plugins.ext && cp -p ../plugins.ext . || cp -p ../../plugins.ext .)
test -f config.h || ../../../../platforms/unix/config/configure \
		--with-vmversion=5.0 \
		--with-src=src/spur64.cog.newspeak \
		--without-vm-display-fbdev --without-npsqueak \
	TARGET_ARCH="-m64" \
	CC=clang \
	CFLAGS="$OPT -DEnforceAccessControl=0 -msse2 -DITIMER_HEARTBEAT=1"
rm -f vm/sqUnixMain.o # nuke version info
rm -rf ../../../../products/$INSTALLDIR
make install-squeak install-plugins prefix=`(cd ../../../../;pwd)`/products/$INSTALLDIR 2>&1 | tee LOG ; test ${PIPESTATUS[0]} -eq 0
../../editnewspeakinstall.sh ../../../../products/$INSTALLDIR -source SqueakV41 "$@"
