#!/bin/sh
# Some gcc versions create a broken VM using -O2
case `gcc -v 2>&1 | grep version | sed 's/gcc version *//'` in
3.4.*)	OPT=-O1;;
*)		OPT=-O2;;
esac

echo -n "clean? "
read a
case $a in
n|no|N|NO)	echo "ok but this isn't safe!!";;
*)			make reallyclean
esac
test -f config.h || ../../platforms/unix/config/configure --without-npsqueak CFLAGS="-g $OPT -msse2 -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -DNDEBUG -DITIMER_HEARTBEAT=1 -DNO_VM_PROFILE=1 -DCOGMTVM=0 -DDEBUGVM=0" LIBS=-lpthread
../../scripts/nukeversion
rm -rf ../../coglinux
make install prefix=`(cd ../../;pwd)`/coglinux
