PLUGIN_REQUIRE_LIBRARY (PTHREAD pthread)
PLUGIN_INCLUDE_DIRECTORIES (${cross}/plugins/FilePlugin ${cross}/plugins/SocketPlugin)
PLUGIN_DEFINITIONS (-DSQAIO_H=\"sqaio.h\")

CHECK_FUNCTION_EXISTS (unsetenv HAVE_UNSETENV)

CONFIG_DEFINE (HAVE_UNSETENV)
