Extension { #name : #DummyStream }

{ #category : #'*CogBenchmarks-Shootout-platform' }
DummyStream >> cr [
]

{ #category : #'*CogBenchmarks-Shootout-platform' }
DummyStream >> nl [
	"do nothing"
]

{ #category : #'*CogBenchmarks-Shootout-platform' }
DummyStream >> print: number digits: decimalPlaces [
	"do nothing"
]

{ #category : #'*CogBenchmarks-Shootout-platform' }
DummyStream >> print: number paddedTo: width [
	"do nothing"
]

{ #category : #'*CogBenchmarks-Shootout-platform' }
DummyStream >> space [
]

{ #category : #'*CogBenchmarks-Shootout-platform' }
DummyStream >> tab [
]
