##############################################################################
# Makefile for Mac OS X Stack Spur Newspeak Cocoa VM using clang and gnu make 3.81
# Do make init to allow make -n to function.
#

VMSRCDIR:= ../../../src/spur32.stack.newspeak

include ../common/Makefile.app.newspeak
