##############################################################################
# Makefile for Mac OS X Stack Spur Squeak Cocoa VM using clang and gnu make 3.81
# Do make init to allow make -n to function.
#

VMSRCDIR:= ../../spurstacksrc/vm
SOURCEFILE:=SqueakV50.sources

# Now include the Makefile proper, which is common to all Mac OS builds.
#
include ../common/Makefile.app
