#!/bin/sh
# VM with VM profiler and threaded heartbeat assuming multiple thread priorities
INSTALLDIR=cogspurastlinuxht
if [ $# -ge 1 ]; then
	INSTALLDIR="$1"; shift
fi
echo -n "clean? "
read a
case $a in
n|no|N|NO)	echo "ok but this isn't safe!!";;
*)			test -f Makefile && make reallyclean
esac
test -f config.h || ../../../platforms/unix/config/configure --with-src=spursrc --with-plugins=src/plugins --without-npsqueak \
	CC="gcc -m32" \
	CFLAGS="-g3 -O1 -msse2 -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -DCOGMTVM=0 -DDEBUGVM=0" \
	LIBS=-lpthread \
	LDFLAGS=-Wl,-z,now
../../../scripts/nukeversion
rm -rf ../../../$INSTALLDIR
make install prefix=`(cd ../../../;pwd)`/$INSTALLDIR
