#!/bin/sh
D=
A=
F=
DT=
AT=
FT=
H=
C=
while [ -n "$1" ]; do
	case $1 in
	-c)	C=-c;; #-c == Core VM only
#	-A)	D=LOGD;A=LOGA;F=LOGS;DT=LOGTD;AT=LOGTA;FT=LOGTS;;
#	-AS)	D=LOGD;A=LOGA;F=LOGS;;
	-A|-AS)	D=LOGD;A=LOGA;F=LOGS;;
	-AT)	DT=LOGTD;AT=LOGTA;FT=LOGTS;;
	-d)	D=LOGD;;
	-dt)	DT=LOGTD;;
	-a)	A=LOGA;;
	-at)	AT=LOGTA;;
	-f)	F=LOGF;;
	-ft)	FT=LOGTF;;
	-?|-h)	H=h
	esac
	shift
done
if [ -n "$H" -o -z "$D$A$F$DT$AT$FT" ]; then
	echo usage: $0 -A \| -AS -AT \| -d -a -f -dt -at -ft
	exit 1
fi
trap 'exit 2' HUP INT PIPE TERM
test -n "$D" && (makevm $C -d 2>&1 | tee $D;grep "BUILD .*ED" $D)
test -n "$A" && (makevm $C -a 2>&1 | tee $A;grep "BUILD .*ED" $A)
test -n "$F" && (makevm $C -s 2>&1 | tee $F;grep "BUILD .*ED" $F)
test -n "$DT" && (makevm $C -md 2>&1 | tee $DT;grep "BUILD .*ED" $DT)
test -n "$AT" && (makevm $C -ma 2>&1 | tee $AT;grep "BUILD .*ED" $AT)
test -n "$FT" && (makevm $C -ms 2>&1 | tee $FT;grep "BUILD .*ED" $FT)

test -n "$D" && (echo $D;grep "BUILD .*ED" $D)
test -n "$A" && (echo $A;grep "BUILD .*ED" $A)
test -n "$F" && (echo $F;grep "BUILD .*ED" $F)
test -n "$DT" && (echo $DT;grep "BUILD .*ED" $DT)
test -n "$AT" && (echo $AT;grep "BUILD .*ED" $AT)
test -n "$FT" && (echo $FT;grep "BUILD .*ED" $FT)
