#!/bin/sh
INSTALLDIR=cogastlinux
if [ $# -ge 1 ]; then
	INSTALLDIR="$1"; shift
fi
echo -n "clean? "
read a
case $a in
n|no|N|NO)	echo "ok but this isn't safe!!";;
*)			test -f Makefile && make reallyclean
esac
test -f config.h || ../../platforms/unix/config/configure --without-npsqueak \
	CC="gcc -m32" \
	CFLAGS="-g3 -O1 -msse2 -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -DITIMER_HEARTBEAT=1 -DCOGMTVM=0 -DDEBUGVM=0" \
	LIBS="-lpthread -luuid" \
	LDFLAGS=-Wl,-z,now
../../scripts/nukeversion
rm -rf ../../$INSTALLDIR
make install prefix=`(cd ../../;pwd)`/$INSTALLDIR
