#!/bin/bash
# debug Stack Spur VM with VM profiler and threaded heartbeat
INSTALLDIR=debug/nsstkspurlinuxht
OPT="-g3 -O0 -DDEBUGVM=1"

if [ $# -ge 1 ]; then
	case "$1" in
	-*)	;;
	*)	INSTALLDIR="$1"; shift
	esac
fi
echo -n "clean? "
read a
case $a in
n|no|N|NO)	echo "ok but this isn't safe!!";;
*)			rm config.h; test -f Makefile && make reallyclean
esac
test -f config.h || ../../../platforms/unix/config/configure \
		--with-src=nsspurstacksrc  --with-plugin-src=nscogsrc/plugins --disable-cogit \
	CC="gcc -m32" \
	CFLAGS="$OPT -msse2 -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64" \
	LIBS="-lpthread -luuid" \
	LDFLAGS=-Wl,-z,now
../../../scripts/nukeversion
rm -rf ../../../products/$INSTALLDIR
# would prefer make install prefix=`readlink -f \`pwd\`/../../products/$INSTALLDIR`
# but older linux readlinks lack the -f flag
make install prefix=`(cd ../../../;pwd)`/products/$INSTALLDIR
../../editnewspeakinstall.sh ../../../products/$INSTALLDIR
