CHECK_INCLUDE_FILE (util.h	HAVE_UTIL_H)
CHECK_INCLUDE_FILE (libutil.h	HAVE_LIBUTIL_H)
CHECK_INCLUDE_FILE (pty.h	HAVE_PTY_H)
CHECK_INCLUDE_FILE (stropts.h	HAVE_STROPTS_H)

# can't include libutil.h by itself on FreeBSD because of missing defns
IF (NOT HAVE_LIBUTIL_H AND EXISTS /usr/include/libutil.h)
  SET (HAVE_LIBUTIL_H 1)
ENDIF ()

CHECK_LIBRARY_EXISTS (util openpty "" HAVE_OPENPTY)
IF (NOT HAVE_OPENPTY)
    IF (EXISTS /dev/ptmx)
        CHECK_FUNCTION_EXISTS (grantpt, HAVE_UNIX98_PTYS)
	IF (NOT HAVE_UNIX98_PTYS)
	    DISABLE_PLUGIN ()
	ENDIF (NOT HAVE_UNIX98_PTYS)
    ENDIF (EXISTS /dev/ptmx)
ENDIF (NOT HAVE_OPENPTY)

CONFIG_DEFINE (HAVE_UTIL_H)
CONFIG_DEFINE (HAVE_LIBUTIL_H)
CONFIG_DEFINE (HAVE_PTY_H)
CONFIG_DEFINE (HAVE_STROPTS_H)

CONFIG_DEFINE (HAVE_OPENPTY)
CONFIG_DEFINE (HAVE_UNIX98_PTYS)
