#!/bin/bash
trap 'exit 2' HUP INT PIPE TERM
PRODUCTDIRS="newspeak.cog.spur pharo.cog.spur squeak.cog.spur squeak.cog.v3"
for d in $PRODUCTDIRS; do
	if test -d "$d"; then
		(cd ./$d;./mvm -A)
	else
		echo no $d directory found
	fi
done
echo no news is good news...
for d in $PRODUCTDIRS; do
	test -d $d && grep 'BUILD FAILED' $d/LOG*
done
