#!/bin/bash -e
trap 'exit 2' HUP INT PIPE TERM
DIRS="squeak.sista.spur"
for d in $DIRS; do
	if test -d "$d"; then
		(cd ./$d;./mvm -A)
	else
		echo no $d directory found
	fi
done
echo no news is good news...
for d in $DIRS; do
	test -d $d && grep -w error: $d/LOG*
done
