#!/bin/bash
trap 'exit 2' HUP INT PIPE TERM
for d in newspeak.* squeak.*; do
	if test -d "$d"; then
		(cd $d;./mvm -A)
	else
		echo no $d directory found
	fi
done
echo no news is good news...
grep 'BUILD FAILED' newspeak.*/LOG* squeak.*/LOG*
