#!/bin/bash
IFS="
	"
trap 'exit 2' HUP INT PIPE TERM 0
REV=`grep 'SvnRawRevisionString.*Rev:' "\`dirname $0\`/../platforms/Cross/vm/sqSCCSVersion.h" \
	| sed 's/^.*Rev: \([0-9][0-9]*\) $";/\1/'`
TAG=`date +%g.%U.`$REV
set -- Newspeak\ Virtual\ Machine	Newspeak\ Spur\ Virtual\ Machine	\
		Cog		Cog\ Spur
for td in newspeak.cog.v3 newspeak.cog.spur squeak.cog.v3 squeak.cog.spur; do
	d=$td/installer
	PRODUCT=$1-$TAG.dmg
	if test -d "$d"; then
		(cd $d;make -n)
		test -f $d/$PRODUCT && mv $d/$PRODUCT ../products
	else
		echo no $d directory found
	fi
	shift
done
