#############################################################################
# Makefile for Win32 Stack Squeak VM using gcc-3.4.x and cygwin
# Do make init to allow make -n to function.
#############################################################################

VM:=Squeak
VMSRCDIR:=../../stacksrc/vm

include ../common/Makefile
