GDBBUILDFOLDER	= $(topdir)/../gdb
XCFLAGS		= -m32 -DNEED_UI_LOOP_HOOK

XINCLUDES	+= -I$(GDBBUILDFOLDER)/sim/arm
XINCLUDES	:= -I$(GDBBUILDFOLDER)/bfd $(XINCLUDES)

XLDFLAGS=	$(GDBBUILDFOLDER)/sim/arm/libsim.a \
		$(GDBBUILDFOLDER)/opcodes/libopcodes.a \
		-lbfd -liberty \
		-Wl,-wrap,ARMul_OSHandleSWI
