##############################################################################
# Makefile for Mac OS X Cog V3 Squeak Cocoa VM using clang and gnu make 3.81
# Do make init to allow make -n to function.
#

VMSRCDIR:= ../../src/vm
SOURCEFILE:=SqueakV46.sources

# Now include the Makefile proper, which is common to all Mac OS builds.
#
include ../common/Makefile.app.squeak
