#############################################################################
# Common Makefile for Win64ARMv8 VM using LLVM/Clang compiler, MSYS2 toolchain,
# and mingw-w64 for building a native Windows application.
#
# Copyright (c) Andreas Raab, Eliot Miranda, Marcel Taeumel, et al. 
# Copyright (c) 2025 Hasso Plattner Institute, University of Potsdam, Germany
#############################################################################

ARCH:=arm64
export ARCH

TOOLPREFIX:=aarch64-w64-mingw32-
export TOOLPREFIX

#############################################################################
# C compiler settings (Use clang for having a working FFI)
#
CC:= $(TOOLPREFIX)clang
CXX:= $(TOOLPREFIX)clang++

TZ:=$(shell date +%Z)

#############################################################################
# Linker settings
#
LD:=$(CC)
LDCXX:=$(CXX) # For linking c++ bundles

EXPORT:=--export-all-symbols
BASELDFLAGS:=-m64 -mthreads -Wl,--stack -Xlinker 2097152,2097152 -Wl,$(EXPORT)
LDFLAGS:= -mwindows $(BASELDFLAGS)
CONSOLELDFLAGS:= -mconsole $(BASELDFLAGS)
STDLIBS:= -lddraw -ldinput -lopengl32 -lws2_32 -lcomdlg32 -lole32 -lwinmm \
	-lversion -lwininet -luser32 -lgdi32 -lpsapi -lkernel32 \
	-ldsound -lsecur32 -lshfolder

#############################################################################
# Tools to use
# - Note that "dllwrap" is replaced by "clang -shared"
# - Note that "ar" produces thin archives (-T) to allow mising .o and .a
#
AR:= $(TOOLPREFIX)ar crUuT
CP:= cp
RM:= rm
SED:=sed
MV:=mv
MKDIR:=mkdir -p
NM:= $(TOOLPREFIX)nm
DLLTOOL:=	$(TOOLPREFIX)dlltool
DLLWRAP:=	$(CC) -shared
STRIP:= 	$(TOOLPREFIX)strip
OBJCOPY:=	$(TOOLPREFIX)objcopy

#############################################################################
# RC settings
#
# Note: RC compiles the .rc files into linkable .o files
#
RC:=$(TOOLPREFIX)windres
SCCSVER:=$(PLATDIR)/Cross/vm/sqSCCSVersion.h

ifneq ($(shell grep 'GitRawRevisionString.*$$Rev$$.' $(SCCSVER)),)
$(shell bash -c "cd ../../../scripts; ./updateSCCSVersions")
endif
SVNMAJOR := $(shell $(SED) -e "s/^static.*GitRawRevisionString.*Rev: \([0-9][0-9][0-9][0-9]\).*/\\1/p" -e d $(SCCSVER) | $(SED) -e 's/^0*//')
SVNMINOR := $(shell $(SED) -e "s/^static.*GitRawRevisionString.*Rev: [0-9][0-9][0-9][0-9]\([0-9][0-9]\).*/\\1/p" -e "s/^0*//" -e d $(SCCSVER) | $(SED) -e 's/^0*//')
SVNREV := $(shell $(SED) -e "s/^static.*GitRawRevisionString.*Rev: [0-9][0-9][0-9][0-9][0-9][0-9]\([0-9][0-9]\).*/\\1/p" -e "s/^0*//" -e d $(SCCSVER) | $(SED) -e 's/^0*//')
SVNBUILD := $(shell $(SED) -e "s/^static.*GitRawRevisionString.*Rev: [0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]\([0-9][0-9]*\).*/\\1/p" -e "s/^0*//" -e d $(SCCSVER) | $(SED) -e 's/^0*//')

RCFLAGS:= --include-dir $(PLATDIR)/win32/misc -D_WIN32 -DFILEVERSIONVALUES=$(SVNMAJOR),$(SVNMINOR),$(SVNREV),$(SVNBUILD) '-DFILEVERSIONSTRING=\"$(SVNMAJOR).$(SVNMINOR).$(SVNREV).$(SVNBUILD)\\0\"'
