PLUGIN_FIND_INCLUDE (SYS_AUDIOIO sys/audioio.h)
PLUGIN_FIND_INCLUDE (SUN_AUDIOIO sun/audioio.h)

IF (NOT HAVE_SYS_AUDIOIO_H AND NOT HAVE_SUN_AUDIOIO_H)
  PLUGIN_DISABLE ()
ENDIF ()

CONFIG_DEFINE (HAVE_SYS_AUDIOIO_H)
