##############################################################################
# Makefile for Mac OS X Cog Spur Newspeak Cocoa VM using clang and gnu make 3.81
# Do make init to allow make -n to function.
#

VMSRCDIR:= ../../../src/newspeak.vm.64bit.cog.spur

include ../common/Makefile.app.newspeak
