#############################################################################
# Makefile for Win32 Cog Spur PharoVM using gcc-3.4.x and cygwin
# Do make init to allow make -n to function.
#############################################################################

VM:=Pharo
VM_NAME:=Pharo Virtual Machine
	
VMSRCDIR:=../../spursrc/vm
COGDEFS:=-DPharoVM=1

include ../common/Makefile
