#############################################################################
# Compilation rules for Microsoft Windows
#
# See http://make.mad-scientist.net/papers/advanced-auto-dependency-generation
# for an explanation of the dependency management scheme.

DEPFLAGS = -MT $@ -MMD -MP -MF deps/$(*F).Td
ALLFLAGS = $(DEPFLAGS) $(CFLAGS) $(INCLUDES) $(DEFS)
POSTCOMPILE = sed '/^$$/d' <deps/$(*F).Td | sed '/^.*:$$/d' | sed 's/ [^ ]*:/:/' | sed 's/^build[^/]*/$$(BUILD)/' > deps/$(*F).d; rm deps/$(*F).Td; touch -r $< deps/$(*F).d

$(OBJDIR)/%.o: %.c deps/%.d
	$(CC) -x c $(ALLFLAGS) -c $< -o $@
	$(POSTCOMPILE)

$(OBJDIR)/%.o: %.m deps/%.d
	$(CC) -x objective-c $(ALLFLAGS) -c $< -o $@
	$(POSTCOMPILE)

$(OBJDIR)/%.o: %.cpp deps/%.d
	$(CXX) $(ALLFLAGS) -c $< -o $@
	$(POSTCOMPILE)

%res: %.rc
	$(RC) $(RCFLAGS) -i $< -o $@


deps/%.d: ;

.PRECIOUS: deps/%.d

-include $(patsubst %,deps/%.d,$(notdir $(basename $(VMSRC))))

#.cpp.o:
#		$(CXX) -c $(CXXFLAGS) $(CXXINCLUDES) $<
#
