#!/bin/sh
rm -rf build*/vm/nsvm*.exe
make debug;make assert;make
ls -rlt build*/vm/nsvm*.exe
if [ ! -f builddbg/vm/SqueakV41.sources \
  -a ! -f buildast/vm/SqueakV41.sources \
  -a ! -f build/vm/SqueakV41.sources ]; then
	echo "don't forget to link in sources!!"
else
	if [ ! -f builddbg/vm/SqueakV41.sources ]; then
		echo "don't forget to link in builddbg/vm sources"
	fi
	if [ ! -f buildast/vm/SqueakV41.sources ]; then
		echo "don't forget to link in buildast/vm sources"
	fi
	if [ ! -f build/vm/SqueakV41.sources ]; then
		echo "don't forget to link in build/vm sources"
	fi
fi
