"
A Linux32x86NewspeakCogV3AssertConfig  configures a VM according to my name's form: [Operating System] [WordSize] [Processor Language][VM MemoryManager][BuildType]Conf

Usage:
 Linux32x86NewspeakCogV3AssertConfig generate
Or:
 Linux32x86NewspeakCogV3AssertConfig generateWithSources
Or:
find my Builder in CMakeVMMakerSqueak-Builder category and use that to query me or invoke me
"
Class {
	#name : #Linux32x86NewspeakCogV3AssertConfig,
	#superclass : #Linux32x86NewspeakCogV3Config,
	#category : #'CMakeVMMakerSqueak-Linux32x86'
}

{ #category : #'as yet unclassified' }
Linux32x86NewspeakCogV3AssertConfig >> todo [
	self flag:'tty'
]
