##############################################################################
# Makefile for Mac OS X Cog Spur Pharo Cocoa VM using clang and gnu make 3.81
# Do make init to allow make -n to function.
#

VMSRCDIR:= ../../spur64src/vm
VM:=Pharo
CFLAGS:=-DPharoVM=1

# Now include the Makefile proper, which is common to all Mac OS builds.
#
include ../common/Makefile.app
