#!/usr/bin/env bash
set -e
# assert VM with VM profiler and threaded heartbeat
INSTALLDIR=assert/sqcogspur32linuxhtRPi
OPT="-g3 -O1 -DDEBUGVM=0"

if [ $# -ge 1 ]; then
	INSTALLDIR="$1"; shift
fi

if ../../../../scripts/checkSCCSversion ; then exit 1; fi
echo -n "clean? "
read a
case $a in
n|no|N|NO)	echo "ok but this isn't safe!!";;
*)			test -f Makefile && make reallyclean
esac
../../../../scripts/copylinuxpluginspecfiles
test -f config.h || ../../../../platforms/unix/config/configure --without-npsqueak \
		--with-vmversion=5.0 --with-src=src/spur32.cog \
		--without-npsqueak --enable-fast-bitblt \
		--with-scriptname=spur32 \
	TARGET_ARCH="-march=armv6 -mfpu=vfp -mfloat-abi=hard" \
	CFLAGS="$OPT -DI_REALLY_DONT_CARE_HOW_UNSAFE_THIS_IS -DUSE_MIDI_ALSA -DCOGMTVM=0"
rm -f vm/sqUnixMain.o # nuke version info
rm -rf ../../../../products/$INSTALLDIR
# prefer make install prefix=`readlink -f \`pwd\`/../../../../products/$INSTALLDIR`
# but older linux readlinks lack the -f flag and Raspbian lacks `readlinks`
make -j4 install-squeak install-plugins prefix=`(cd ../../../../;pwd)`/products/$INSTALLDIR 2>&1 | tee LOG ; test ${PIPESTATUS[0]} -eq 0
