#!/usr/bin/env bash
set -e
trap 'exit 2' HUP INT PIPE TERM
PRODUCTDIRS="newspeak.cog.spur squeak.cog.spur squeak.cog.v3 pharo.cog.spur"
for d in $PRODUCTDIRS; do
	if test -d "$d"; then
		(echo $d;cd ./$d;./mvm -A)
	else
		echo no $d directory found
	fi
done
echo no news is good news...
for d in $PRODUCTDIRS; do
	test -d $d && grep -w error: $d/LOG*
done
