#!/bin/bash
# debug Spur VM with VM profiler and threaded heartbeat
INSTALLDIR=debug/cogspurlinuxhtARM
OPT="-g3 -O0 -DDEBUGVM=1"

if [ $# -ge 1 ]; then
	INSTALLDIR="$1"; shift
fi

echo -n "clean? "
read a
case $a in
n|no|N|NO)	echo "ok but this isn't safe!!";;
*)			test -f Makefile && make reallyclean
esac
test -f config.h || ../../../platforms/unix/config/configure --without-npsqueak \
		--without-vm-display-fbdev --with-vmversion=5.0 \
		--with-src=spursrc --with-plugins=src/plugins \
	CC=gcc \
	CXX=g++ \
	CFLAGS="$OPT -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64  -DI_REALLY_DONT_CARE_HOW_UNSAFE_THIS_IS -DCOGMTVM=0" \
	LIBS="-lpthread -luuid -lasound" \
	LDFLAGS=-Wl,-z,now
rm -f vm/sqUnixMain.o # nuke version info
rm -rf ../../../products/$INSTALLDIR
# prefer make install prefix=`readlink -f \`pwd\`/../../../products/$INSTALLDIR`
# but older linux readlinks lack the -f flag and Raspbian lacks `readlinks`
make -j4 install-squeak install-plugins prefix=`(cd ../../../;pwd)`/products/$INSTALLDIR 2>&1 | tee LOG
