#!/bin/bash -e
# PharoVM with VM profiler and threaded heartbeat
THIRDPARTYLIBS="libsdl2 openssl libssh2 libgit2"
INSTALLDIR=debug/phcogspur64linuxht

if [ $# -ge 1 ]; then
	INSTALLDIR="$1"; shift
fi

if ../../../../scripts/checkSCCSversion ; then exit 1; fi
echo -n "clean? "
read a
case $a in
n|no|N|NO)	echo "ok but this isn't safe!!";;
*)		
	test -f Makefile && make clean
#	for lib in ${THIRDPARTYLIBS}; do
#		../../third-party/mvm ${lib} clean
#	done
esac

for lib in ${THIRDPARTYLIBS}; do
	../../third-party/mvm ${lib}
done

LDFLAGS="-L../../../../.thirdparty-cache/linux/x86_64/lib" \
CC=clang \
CFLAGS="-I../../../../.thirdparty-cache/linux/x86_64/include -I../../../.thirdparty-cache/linux/x86_64/include/SDL2" \
	cmake \
		-DCMAKE_BUILD_TYPE=Debug \
		-DBUILD_I386_VERSION=OFF \
		-DSDL2_INCLUDE_DIR=../../../../.thirdparty-cache/linux/x86_64/include/SDL2 \
		-DSDL2_LIBRARY_PATH=../../../../.thirdparty-cache/linux/x86_64/lib \
		../../.. 
make

productDir=`find ../../../../products/$INSTALLDIR -name "5.0*"`
productDir=`(cd $productDir;pwd)`
for lib in ${THIRDPARTYLIBS}; do
	../../third-party/mvm ${lib} install $productDir
done
cp dist/* $productDir
../../editpharoinstall.sh ../../../../products/$INSTALLDIR "$@"
