#!/usr/bin/env bash
set -e
# debug Stack Spur VM with VM profiler and threaded heartbeat
INSTALLDIR=debug/nsstkspur32linuxhtARMv7
OPT="-g3 -O0 -DDEBUGVM=1"

if [ $# -ge 1 ]; then
	INSTALLDIR="$1"; shift
fi

if ../../../../scripts/checkSCCSversion ; then exit 1; fi
echo -n "clean? "
read a
case $a in
n|no|N|NO)	echo "ok but this isn't safe!!";;
*)			rm -f config.h; test -f Makefile && make reallyclean
esac
../../../../scripts/copylinuxpluginspecfiles
test -f config.h || ../../../../platforms/unix/config/configure \
	--with-vmversion=5.0 \
	--with-src=src/spur32.stack.newspeak --disable-cogit \
	--without-vm-display-fbdev --without-npsqueak \
	CFLAGS="$OPT"
rm -f vm/sqUnixMain.o # nuke version info
rm -rf ../../../../products/$INSTALLDIR
# prefer make install prefix=`readlink -f \`pwd\`/../../../../products/$INSTALLDIR`
# but older linux readlinks lack the -f flag and Raspbian lacks `readlinks`
make -j4 install-squeak install-plugins prefix=`(cd ../../../../;pwd)`/products/$INSTALLDIR 2>&1 | tee LOG ; test ${PIPESTATUS[0]} -eq 0
../../editnewspeakinstall.sh ../../../../products/$INSTALLDIR "$@"
