#!/bin/sh
# List any files with an un-checked-in package version comment "* VMMaker-..."

find ${@-src/plugins/* src/v3* src/spur*} -type f -a -name '*.[ch]' \
		-exec egrep -l 'char __buildInfo\[][^*]*\*| \* [A-Za-z.0-9_-]* uuid: ' {} \;
