#!/bin/sh
# List any files with an un-checked-in package version comment "* VMMaker-..."
find ${@-src nscogsrc stacksrc spursrc spurstacksrc nsspursrc nsspurstacksrc} -name .svn -prune -o \( -type f -a -name '*.[ch]' \) \
		-exec egrep -l '\* VMMaker|\* VMConstruction' {} \;
