#!/bin/sh
# checkin script for Git that serves to cause
# platforms/Cross/vm/sqSCCSVersion.h to be checked-in so that its version
# info reflects that of the current check-in.
rm -rf src/plugins/[A-Z]*FFIPlugin
`dirname $0`/revertUnchangedPlugins src/plugins
# make sure that we enable our smudge and clean filters
# these replace occurances of $Rev$, $URL$, and $Date$ in
# locally checked out sqSCCSVersion.h and sqPluginsSCSSVersion.h
# with useful values
if [ -z "$@"  ]; then
    GIT_ARGS="-A"
else
    GIT_ARGS=$@
fi

git add $GIT_ARGS
git reset HEAD -- platforms/Cross/plugins/*
git reset HEAD -- platforms/win32/plugins/*
git commit

`dirname $0`/updateSCCSVersions
