#!/bin/sh
# Create the Cog VM archives in products.  Check the log files in products for
# agreement
`dirname $0`/mkcogvmarchives
`dirname $0`/mkspurvmarchives
echo "Version info:"
cat `dirname $0`/../products/M[CS]VALOG | egrep '\$Rev|VMMaker' | sort -u
