#!/bin/sh
# Nuke the built on version info in object files.
case `basename \`pwd\`` in
*macbuild)		find build -name version.o -print -exec rm {} \; ;;
cygwinbuild)	echo not needed on Windows.  Build does it automatically;;
*unixbuild)		find . -name sqUnixMain.o -print -exec rm {} \; ;;
*linuxbuild)	find . -name sqUnixMain.o -print -exec rm {} \; ;;
esac
case `basename \`dirname \\\`pwd\\\`\`` in
*unixbuild)		find . -name sqUnixMain.o -print -exec rm {} \; ;;
*linuxbuild)	find . -name sqUnixMain.o -print -exec rm {} \; ;;
esac
case `basename \`dirname \\\`dirname \\\\\\\`pwd\\\\\\\`\\\`\`` in
build.linux*)	find . -name sqUnixMain.o -print -exec rm {} \; ;;
esac
