#!/bin/bash -e
# Print REV and TAG as defined in platforms/Cross/vm/sqSCCSVersion.h

# cd `dirname $0`/../products

test -n "$REV" || REV=`grep 'GitRawRevisionString.*Rev:' $(dirname $0)/../platforms/Cross/vm/sqSCCSVersion.h \
	| sed 's/^.*Rev: \([0-9][0-9]*\).* $";/\1/'`
test -n "$TAG" || TAG=`date +%y.%U.`$REV
echo REV=$REV TAG=$TAG
