#!/bin/sh
# Revert any and all plugins whose changes comprise only the generation metadata
# such as date generated, VMMaker version etc.

#IFS=<tab><nl>
IFS='	
'
if [ $# = 0 ]; then
PD=src/plugins
else
PD=$1
fi
for d in $PD/[A-Z]*
do
	test -d "$d" || continue
	find "$d" -name .svn -prune -o \( -type f -a -name '*.[ch]' \) -exec \
		scripts/revertIfEssentiallyUnchanged {} \;
done
