#!/bin/sh
# Revert the argument if its changes comprise only the generation metadata
# such as date generated, VMMaker version etc.

if [ -d "$1" ]; then
	$0 `svn st "$1" | grep "^M" | sed 's/^M *//'`
	exit 0
fi
case `svn st "$1"` in
M*)	;;
*)	exit 0
esac
test -z "`svn diff \"$1\" | grep '^[+-]' | egrep -v ' VMMaker[-.][a-z][a-z-]*\.[0-9][0-9]* uuid:| Cog[-.][a-z][a-z]*\.[0-9][0-9]* uuid:| Qwaq-Plugins[-.][a-z][a-z]*\.[0-9][0-9]* uuid:| VMMaker[-.][a-z][a-z-]*\.[0-9][0-9]* \([ie]\)| Cog[-.][a-z][a-z-]*\.[0-9][0-9]* \([ie]\)| Qwaq-Plugins[-.][a-z][a-z]*\.[0-9][0-9]* \([ie]\)| VMConstruction-Plugins-OSProcessPlugin[a-z.-][a-z.-]*\.[0-9][0-9]* |^-\-\-|^+\+\+|^[+-]$'`" && svn revert "$1"
