#!/bin/sh
IFS="	
"
if [ $# = 0 ]; then
ARCHIVES="Cog.app.tgz	coglinux.tgz	cogwin.zip	Newspeak Virtual Machine.app.tgz	nsvmlinux.tgz	nsvmwin.zip"
else
ARCHIVES=
	while [ -n "$1" ]; do
		case $1 in
		-c)		ARCHIVES="$ARCHIVES	coglinux.tgz	Cog.app.tgz	cogwin.zip	cogmtlinux.tgz	CogMT.app.tgz	cogmtwin.zip";;
		-cl)	ARCHIVES="$ARCHIVES	coglinux.tgz";;
		-cm)	ARCHIVES="$ARCHIVES	Cog.app.tgz";;
		-cw)	ARCHIVES="$ARCHIVES	cogwin.zip";;
		-ctl)	ARCHIVES="$ARCHIVES	cogmtlinux.tgz";;
		-ctm)	ARCHIVES="$ARCHIVES	CogMT.app.tgz";;
		-ctw)	ARCHIVES="$ARCHIVES	cogmtwin.zip";;
		-nl)	ARCHIVES="$ARCHIVES	nsvmlinux.tgz";;
		-nm)	ARCHIVES="$ARCHIVES	Newspeak Virtual Machine.app.tgz";;
		-nw)	ARCHIVES="$ARCHIVES	nsvmwin.zip";;
		-n)		ARCHIVES="$ARCHIVES	nsvmlinux.tgz	Newspeak Virtual Machine.app.tgz	nsvmwin.zip";;
		-l)		ARCHIVES="$ARCHIVES	coglinux.tgz	nsvmlinux.tgz";;
		-m)		ARCHIVES="$ARCHIVES	Cog.app.tgz	Newspeak Virtual Machine.app.tgz";;
		-w)		ARCHIVES="$ARCHIVES	cogwin.tgz	nsvmwin.tgz";;
		-?|-h)  echo usage: $0 [-l -m -w -cl -cm -cw -nl -nm -nw]; exit 0
		esac
		shift
	done
fi
VER="`svnversion | sed 's/^.*://'`"
echo $VER
test -f README.$VER || vi README.$VER
ssh -x eliotmiranda@bugsy.dreamhost.com mkdir mirandabanda.org/files/Cog/VM/VM.r$VER
scp README.$VER $ARCHIVES eliotmiranda@bugsy.dreamhost.com:mirandabanda.org/files/Cog/VM/VM.r$VER
