#!/bin/sh
# Upload archives from products to a web/ftp site via ssh.
RemoteUser=eliotmiranda@highland-park.dreamhost.com
RemoteRoot=mirandabanda.org/files/Cog/VM
IFS="	
"
cd `dirname $0`/../products
VERBOSE=
REV="`svnversion | sed 's/^.*://'`"
case $REV in
*M)	echo -n "source tree is modified, are you sure you want to continue? "
	read a
	case $a in
	y|Y)	;;
	*)		exit 1
	esac
	REV="`svnversion | sed 's/^.*://' | sed 's/M//'`";;
esac
if [ "$1" = "-r" -a -n "$2" ]; then
	REV="$2"
	shift;shift
fi
TAG=`date +%g.%U.`$REV
echo REV=$REV TAG=$TAG

CSARCS="Cog.app-$TAG.tgz	coglinux-$TAG.tgz	coglinuxht-$TAG.tgz	cogwin-$TAG.zip"
CSARCS="$CSARCS	CogSpur.app-$TAG.tgz	cogspurlinuxht-$TAG.tgz	cogspurwin-$TAG.zip"
CMARCS="CogMT.app-$TAG.tgz	cogmtlinuxht-$TAG.tgz	cogmtwin-$TAG.zip"
NSARCS="Newspeak Virtual Machine-$TAG.dmg	nsvmlinux-$TAG.tgz	nsvmlinuxht-$TAG.tgz	nsvm-$TAG.msi"
NSARCS="$NSARCS	Newspeak Spur Virtual Machine-$TAG.dmg	nsvmspurlinuxht-$TAG.tgz	nsvm-$TAG.msi"
#NMARCS="Newspeak Virtual MachineMT-$TAG.dmg	nsvmmtlinux-$TAG.tgz	nsvmmtlinuxht-$TAG.tgz	nsvmmt-spur-$TAG.msi"
if [ $# = 0 ]; then
	ARCHIVES="$CSARCS	$CMARCS		$NSARCS"
	CheckDMG=1
	CheckMSI=1
else
	echo not yet changed
	exit 1
	ARCHIVES=
	CheckDMG=
	CheckMSI=
	while [ -n "$1" ]; do
		case $1 in
		-r)		REV=$1;;
		-c)		ARCHIVES="$ARCHIVES		$CSARCS		$CMARCS";;
		-cl)	ARCHIVES="$ARCHIVES	coglinux-$TAG.tgz	coglinuxht-$TAG.tgz";;
		-cm)	ARCHIVES="$ARCHIVES	Cog.app-$TAG.tgz";;
		-cw)	ARCHIVES="$ARCHIVES	cogwin-$TAG.zip";;
		-ctl)	ARCHIVES="$ARCHIVES	cogmtlinux-$TAG.tgz	cogmtlinuxht-$TAG.tgz";;
		-ctm)	ARCHIVES="$ARCHIVES	CogMT.app-$TAG.tgz";;
		-ctw)	ARCHIVES="$ARCHIVES	cogmtwin-$TAG.zip";;
		-nl)	ARCHIVES="$ARCHIVES	nsvmlinux-$TAG.tgz	nsvmlinuxht-$TAG.tgz";;
		-nm)	ARCHIVES="$ARCHIVES	Newspeak Virtual Machine-$TAG.dmg"
				CheckDMG=1;;
		-nw)	ARCHIVES="$ARCHIVES	nsvm-$TAG.msi"
				CheckMSI=1;;
		-n)		ARCHIVES="$ARCHIVES		$NSARCS";;
		-l)		ARCHIVES="$ARCHIVES	coglinux-$TAG.tgz	coglinuxht-$TAG.tgz	cogmtlinux-$TAG.tgz	cogmtlinuxht-$TAG.tgz	nsvmlinux-$TAG.tgz	nsvmlinuxht-$TAG.tgz";;
		-m)		ARCHIVES="$ARCHIVES	Cog.app-$TAG.tgz	CogMT.app-$TAG.tgz	Newspeak Virtual Machine-$TAG.dmg"
				CheckDMG=1;;
		-v)		VERBOSE=1;;
		-w)		ARCHIVES="$ARCHIVES	cogwin-$TAG.tgz	cogmtwin-$TAG.zip	nsvm-$TAG.msi"
				CheckMSI=1;;
		-?|-h)  echo usage: $0 [-r REV -l -m -w -c -n -cl -cm -cw -ctl -ctm -ctw -nl -nm -nw]; exit 0;;
		*)	break
		esac
		shift
	done
fi
if [ -n "$VERBOSE" ]; then
	for a in $ARCHIVES; do
		echo upload $a
	done
fi
if [ -n "$CheckDMG" -a ! -f "Newspeak Virtual Machine-$TAG.dmg" ]; then
	NMID=nscogbuild/macbuild/installer
	if [ -f "Newspeak Virtual Machine-$TAG.dmg" ]; then
		true
	elif [ -f "$NMID/Newspeak Virtual Machine-$TAG.dmg" ]; then
		ln "$NMID/Newspeak Virtual Machine-$TAG.dmg" .
	else
		echo Newspeak Virtual Machine-$TAG.dmg is missing 1>&2
		exit 1
	fi
fi
if [ -n "$CheckMSI" -a ! -f nsvm-$TAG.msi ]; then
	NWID=nscogbuild/cygwinbuild/installer
	if [ -f nsvm-$TAG.msi ]; then
		true
	elif [ -f "$NWID/nsvm-$TAG.msi" ]; then
		ln "$NWID/nsvm-$TAG.msi" .
	else
		echo nsvm-$TAG.msi is missing 1>&2
		exit 1
	fi
fi
if [ ! -f ../history/README.$REV ]; then
	cat <<THEEND >../history/README.$REV
N.B. For Squeak/Pharo/Croquet please use the archives whose names begin with
     Cog or cog.  The archives whose names begin with nsvm or Newspeak are
     for Newspeak and are missing plugins required by Squeak/Pharo/Croquet.
     VMs with "mt" or "MT" in the name are multi-threaded VMs which support
     non-blocking FFI calls.  The archives containing "Spur" or "spur" are
     VMs using the new Spur object representation and garbage collector and
     should be used with Spur-format Squeak/Pharo/Croquet or Newspeak images.

     There are two variants of the Linux VMs; those ending in "ht" have a
     heartbeat thread, while those that don't, use an interval timer for the
     heartbeat (the Windows and Mac VMs have a threaded heartbeat).  The
     threaded heartbeat is better (for example, signals from the interval timer
     interfere with system calls, etc), but to use it one must have a kernel
     later than 2.6.12 and configure linux to allow the VM to use multiple
     thread priorities.  To do so, create a file called VM.conf where VM is
     the name of the vm executable ("squeak" for the Squeak vm, "nsvm" for
     the Newspeak vm) in /etc/security/limits.d/ with contents:
*       hard    rtprio  2
*       soft    rtprio  2

     e.g.
sudo cat >/etc/security/limits.d/squeak.conf <<END
*       hard    rtprio  2
*       soft    rtprio  2
END
sudo cp /etc/security/limits.d/squeak.conf /etc/security/limits.d/nsvm.conf
     Then log out and log back in for the limits to take effect.

THEEND
	echo getting svn log
	svn log ../platforms/Cross/vm/sqSCCSVersion.h >>../history/README.$REV
	vi ../history/README.$REV
fi
echo compiling ChangeHistory
THEM="`ls ../history/README.* | sort -n -t. -k2 -r`"
>ChangeHistory
for r in $THEM; do
	m="`echo $r | sed 's/..\/history\/README.//'`"
	if [ $REV -ge $m ]; then
		test $REV -ne $m && echo "-------------------------------" >>ChangeHistory
		ls -lT $r | awk '{ print $6, $7, $9; }' >>ChangeHistory
		if grep -s "^------------" $r >/dev/null; then
			awk '{if (line>0) print};/^--------/ {line=1}' $r >>ChangeHistory
		else
			cat $r >>ChangeHistory
		fi
		echo >>ChangeHistory
	fi
done
RemoteUser=eliotmiranda@highland-park.dreamhost.com
RemoteRoot=mirandabanda.org/files/Cog/VM
ssh -x $RemoteUser mkdir $RemoteRoot/VM.r$REV
echo scp -p ChangeHistory ../history/README.$REV $ARCHIVES "$@" $RemoteUser:$RemoteRoot/VM.r$REV
scp -p ChangeHistory ../history/README.$REV $ARCHIVES "$@" $RemoteUser:$RemoteRoot/VM.r$REV
echo ssh $RemoteUser $RemoteRoot/VM.r$REV/* \\\; ls -al $RemoteRoot/VM.r$REV
ash $RemoteUser chmod a-w $RemoteRoot/VM.r$REV/* \; ls -al $RemoteRoot/VM.r$REV
