#!/bin/bash
# Spur VM with VM profiler and itimer heartbeat
INSTALLDIR=cogspurlinux
# Some gcc versions create a broken VM using -O2
case `gcc -v 2>&1 | grep version | sed 's/gcc version *//'` in
3.4.*)	OPT="-g -O1 -DNDEBUG -DDEBUGVM=0";;
*)		OPT="-g -O2 -DNDEBUG -DDEBUGVM=0";;
esac

if [ $# -ge 1 ]; then
	INSTALLDIR="$1"; shift
fi

echo -n "clean? "
read a
case $a in
n|no|N|NO)	echo "ok but this isn't safe!!";;
*)			test -f Makefile && make reallyclean
esac
test -f config.h || ../../../platforms/unix/config/configure --without-npsqueak \
		--with-vmversion=5.0 \
		--with-src=spursrc --with-plugins=src/plugins \
	CC="gcc -m32" \
	CXX="g++ -m32" \
	CFLAGS="$OPT -msse2 -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -DCOGMTVM=0 -DITIMER_HEARTBEAT=1" \
	LIBS="-lpthread -luuid" \
	LDFLAGS=-Wl,-z,now
rm -f vm/sqUnixMain.o # nuke version info
rm -rf ../../../products/$INSTALLDIR
# prefer make install prefix=`readlink -f \`pwd\`/../../../products/$INSTALLDIR`
# but older linux readlinks lack the -f flag
make install prefix=`(cd ../../../;pwd)`/products/$INSTALLDIR 2>&1 | tee LOG
