

vm/vm$a : .force
	@$(SHELL) -ec 'cd vm; $(MAKE) vm$a'

BitBltPlugin/BitBltPlugin$a : .force
	@$(SHELL) -ec 'cd BitBltPlugin; $(MAKE) BitBltPlugin$a'

FileCopyPlugin/FileCopyPlugin$a : .force
	@$(SHELL) -ec 'cd FileCopyPlugin; $(MAKE) FileCopyPlugin$a'

FilePlugin/FilePlugin$a : .force
	@$(SHELL) -ec 'cd FilePlugin; $(MAKE) FilePlugin$a'

FileDialogPlugin/FileDialogPlugin$a : .force
	@$(SHELL) -ec 'cd FileDialogPlugin; $(MAKE) FileDialogPlugin$a'

Float64ArrayPlugin/Float64ArrayPlugin$a : .force
	@$(SHELL) -ec 'cd Float64ArrayPlugin; $(MAKE) Float64ArrayPlugin$a'

FloatArrayPlugin/FloatArrayPlugin$a : .force
	@$(SHELL) -ec 'cd FloatArrayPlugin; $(MAKE) FloatArrayPlugin$a'

FloatMathPlugin/FloatMathPlugin$a : .force
	@$(SHELL) -ec 'cd FloatMathPlugin; $(MAKE) FloatMathPlugin$a'

IA32ABI/IA32ABI$a : .force
	@$(SHELL) -ec 'cd IA32ABI; $(MAKE) IA32ABI$a'

LargeIntegers/LargeIntegers$a : .force
	@$(SHELL) -ec 'cd LargeIntegers; $(MAKE) LargeIntegers$a'

Matrix2x3Plugin/Matrix2x3Plugin$a : .force
	@$(SHELL) -ec 'cd Matrix2x3Plugin; $(MAKE) Matrix2x3Plugin$a'

MiscPrimitivePlugin/MiscPrimitivePlugin$a : .force
	@$(SHELL) -ec 'cd MiscPrimitivePlugin; $(MAKE) MiscPrimitivePlugin$a'

RePlugin/RePlugin$a : .force
	@$(SHELL) -ec 'cd RePlugin; $(MAKE) RePlugin$a'

SecurityPlugin/SecurityPlugin$a : .force
	@$(SHELL) -ec 'cd SecurityPlugin; $(MAKE) SecurityPlugin$a'

SerialPlugin/SerialPlugin$a : .force
	@$(SHELL) -ec 'cd SerialPlugin; $(MAKE) SerialPlugin$a'

SocketPlugin/SocketPlugin$a : .force
	@$(SHELL) -ec 'cd SocketPlugin; $(MAKE) SocketPlugin$a'

StarSqueakPlugin/StarSqueakPlugin$a : .force
	@$(SHELL) -ec 'cd StarSqueakPlugin; $(MAKE) StarSqueakPlugin$a'

SurfacePlugin/SurfacePlugin$a : .force
	@$(SHELL) -ec 'cd SurfacePlugin; $(MAKE) SurfacePlugin$a'

vm-display-null${la} :
	@$(SHELL) -ec 'cd vm-display-null; $(MAKE) vm-display-null${la}'

vm-sound-null${la} :
	@$(SHELL) -ec 'cd vm-sound-null; $(MAKE) vm-sound-null${la}'

FileAttributesPlugin${la} :
	@$(SHELL) -ec 'cd FileAttributesPlugin; $(MAKE) FileAttributesPlugin${la}'

SqueakFFIPrims${la} :
	@$(SHELL) -ec 'cd SqueakFFIPrims; $(MAKE) SqueakFFIPrims${la}'

LocalePlugin${la} :
	@$(SHELL) -ec 'cd LocalePlugin; $(MAKE) LocalePlugin${la}'

VectorEnginePlugin${la} :
	@$(SHELL) -ec 'cd VectorEnginePlugin; $(MAKE) VectorEnginePlugin${la}'
