#!/bin/sh
if [ "$1" = rm -o "$1" = mk ]; then
	rm SqueakV41.sources
fi
if [ "$1" = mk ]; then
	ln ../../../sources/SqueakV41.sources .
fi
if [ \( "$1" != rm \) -a \( "$1" != mk \) ]; then
	echo usage: $0 'mk|rm'
fi
