##############################################################################
# Makefile for Mac OS X Cog Spur Newspeak Cocoa VM using clang and gnu make 3.81
# Do make init to allow make -n to function.
#

VMSRCDIR:= ../../nsspurstacksrc/vm
VM:=Newspeak Virtual Machine
SYSTEM:=Newspeak

# Now include the Makefile proper, which is common to all Mac OS builds.
#
include ../common/Makefile.app
