#!/bin/sh
# Some gcc versions create a broken VM using -O2
case `gcc -v 2>&1 | grep version | sed 's/gcc version *//'` in
3.4.*)	OPT=-O1;;
*)		OPT=-O2;;
esac

test -f config.h || ../../platforms/unix/config/configure INTERP=cointerpmt --without-npsqueak CFLAGS="-g $OPT -msse2 -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -DNDEBUG -DCOGMTVM=1 -DDEBUGVM=0 -D_GNU_SOURCE -DITIMER_HEARTBEAT=1 -DNO_VM_PROFILE=1" LIBS=-lpthread
../../scripts/nukeversion
rm -rf ../../cogmtlinux
make install prefix=`(cd ../../;pwd)`/cogmtlinux
