#ifndef PHAROVM_ERROR_CODES_H
#define PHAROVM_ERROR_CODES_H

#pragma once

typedef enum pharovm_error_code_e
{
    PHAROVM_SUCCESS = 0,
    PHAROVM_ERROR = -1,
    PHAROVM_ERROR_OUT_OF_MEMORY = -2,
    PHAROVM_ERROR_NULL_POINTER = -3,
    PHAROVM_ERROR_EXIT_WITH_SUCCESS = -4,
    PHAROVM_ERROR_INVALID_PARAMETER = -5,
    PHAROVM_ERROR_INVALID_PARAMETER_VALUE = -6
} pharovm_error_code_t;

#endif //PHAROVM_ERROR_CODES_H
