#############################################################################
# Makefile for Win32 Stack Spur Newspeak VM using gcc-3.4.x and cygwin
# Do make init to allow make -n to function.
#############################################################################

# The name of the VM to build
VM:=nsvm
VM_NAME:=Newspeak Virtual Machine

VMSRCDIR:= ../../nsspurstacksrc/vm

include ../common/Makefile
