#!/bin/bash
# debug Stack Spur VM with VM profiler and threaded heartbeat
INSTALLDIR=debug/stkspur64linuxht
OPT="-g3 -O0 -DDEBUGVM=1"

if [ $# -ge 1 ]; then
	INSTALLDIR="$1"; shift
fi

echo -n "clean? "
read a
case $a in
n|no|N|NO)	echo "ok but this isn't safe!!";;
*)			rm config.h; test -f Makefile && make reallyclean
esac
test -f config.h || ../../../platforms/unix/config/configure \
		--with-vmversion=5.0 \
	--with-src=spurstack64src --with-plugins=src/plugins --disable-cogit \
	--without-vm-display-fbdev --without-npsqueak \
	CC="gcc -m64" \
	CXX="g++ -m64" \
	CFLAGS="$OPT -msse2 -D_GNU_SOURCE" \
	LIBS="-lpthread -luuid" \
	LDFLAGS=-Wl,-z,now
rm -f vm/sqUnixMain.o # nuke version info
rm -rf ../../../products/$INSTALLDIR
# prefer make install prefix=`readlink -f \`pwd\`/../../../products/$INSTALLDIR`
# but older linux readlinks lack the -f flag
make install prefix=`(cd ../../../;pwd)`/products/$INSTALLDIR 2>&1 | tee LOG
