#!/bin/sh
# VM with VM profiler and threaded heartbeat assuming multiple thread priorities
INSTALLDIR=coglinuxpt
if [ $# -ge 1 ]; then
	INSTALLDIR="$1"; shift
fi
# Some gcc versions create a broken VM using -O2
case `gcc -v 2>&1 | grep version | sed 's/gcc version *//'` in
3.4.*)	OPT=-O1;;
*)		OPT=-O2;;
esac

echo -n "clean? "
read a
case $a in
n|no|N|NO)	echo "ok but this isn't safe!!";;
*)			make reallyclean
esac
test -f config.h || ../../platforms/unix/config/configure --without-npsqueak \
	CC="gcc -m32" \
	CFLAGS="-g $OPT -msse2 -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -DNDEBUG -DCOGMTVM=0 -DDEBUGVM=0" \
	LIBS=-lpthread \
	LDFLAGS=-Wl,-z,now
../../scripts/nukeversion
rm -rf ../../$INSTALLDIR
make install prefix=`(cd ../../;pwd)`/$INSTALLDIR
