#############################################################################
# Common Makefile for Win64 VM using LLVM/Clang compiler, MSYS2 toolchain,
# and mingw-w64 for building a native Windows application.
#
# Copyright (c) 2025 Hasso Plattner Institute, University of Potsdam, Germany
#############################################################################

ARCH:=x64
export ARCH

TOOLPREFIX:=x86_64-w64-mingw32-
export TOOLPREFIX

#############################################################################
# C compiler settings (Use clang for having a working FFI)
#
CC:= $(TOOLPREFIX)clang
CXX:= $(TOOLPREFIX)clang++

include ../common/Makefile.flags

# VM config flags.
ifeq ($(CONFIGURATION),product)
OFLAGS:=$(PRODUCTION_OFLAGS)
NDEBUG:= -DNDEBUG -D'VM_LABEL(foo)=0' # Define NDEBUG for production to exclude asserts
DEBUGVM=0
else ifeq ($(CONFIGURATION),assert)
OFLAGS:=$(ASSERT_OFLAGS)
DEBUGVM=0
NDEBUG:= -DAllocationCheckFiller=0xADD4E55 -D'VM_LABEL(foo)=0'
else
OFLAGS:=$(DEBUG_OFLAGS)
DEBUGVM=1
NDEBUG:= -DAllocationCheckFiller=0xADD4E55 -D'VM_LABEL(foo)=0'
endif

ifeq ($(IS_PREPARING),false)
  ifeq ($(THREADING),multi)
    COGDEFS:= $(COGDEFS) -DCOGMTVM=1 -DDEBUGVM=$(DEBUGVM)
  else
    COGDEFS:= $(COGDEFS) -DCOGMTVM=0 -DDEBUGVM=$(DEBUGVM)
  endif
  ifdef BIT_IDENTICAL_FLOATING_POINT
    COGDEFS:= $(COGDEFS) -DBIT_IDENTICAL_FLOATING_POINT=1
  endif
endif # IS_PREPARING

include ../common/Makefile.defs.mk

TZ:=$(shell date +%Z)

#############################################################################
# Linker settings
#
# Note: I had to use 'gcc' instead of 'ld' to prevent unresolved symbols
#       The switch '-mwindows' gives us a GUI app instead of a console app.
#		Newer cygwins want --export-all-symbols in place of --export-dynamic.
#
LD:=$(CC)
LDCXX:=$(CXX) # For linking c++ bundles

EXPORT:=--export-all-symbols
BASELDFLAGS:=-m64 -mthreads -Wl,--stack -Xlinker 2097152,2097152 -Wl,$(EXPORT)
LDFLAGS:= -mwindows $(BASELDFLAGS)
CONSOLELDFLAGS:= -mconsole $(BASELDFLAGS)
STDLIBS:= -lddraw -ldinput -lopengl32 -lws2_32 -lcomdlg32 -lole32 -lwinmm \
	-lversion -lwininet -luser32 -lgdi32 -lpsapi -lkernel32 \
	-ldsound -lsecur32 -lshfolder

#############################################################################
# Tools to use
#
AR:= $(TOOLPREFIX)ar rc
ARX:= $(TOOLPREFIX)ar # must not change $(AR) bc. implicit usage
CP:= cp
RM:= rm
SED:=sed
NM:= $(TOOLPREFIX)nm
DLLTOOL:=	$(TOOLPREFIX)dlltool
DLLWRAP:=	$(CC) -shared
STRIP:= 	$(TOOLPREFIX)strip
OBJCOPY:=	$(TOOLPREFIX)objcopy

#############################################################################
# RC settings
#
# Note: RC compiles the .rc files into linkable .o files
#
RC:=	 $(TOOLPREFIX)windres
SCCSVER:=$(PLATDIR)/Cross/vm/sqSCCSVersion.h

ifneq ($(shell grep 'GitRawRevisionString.*$$Rev$$.' $(SCCSVER)),)
$(shell bash -c "cd ../../../scripts; ./updateSCCSVersions")
endif
SVNMAJOR := $(shell $(SED) -e "s/^static.*GitRawRevisionString.*Rev: \([0-9][0-9][0-9][0-9]\).*/\\1/p" -e d $(SCCSVER) | $(SED) -e 's/^0*//')
SVNMINOR := $(shell $(SED) -e "s/^static.*GitRawRevisionString.*Rev: [0-9][0-9][0-9][0-9]\([0-9][0-9]\).*/\\1/p" -e "s/^0*//" -e d $(SCCSVER) | $(SED) -e 's/^0*//')
SVNREV := $(shell $(SED) -e "s/^static.*GitRawRevisionString.*Rev: [0-9][0-9][0-9][0-9][0-9][0-9]\([0-9][0-9]\).*/\\1/p" -e "s/^0*//" -e d $(SCCSVER) | $(SED) -e 's/^0*//')
SVNBUILD := $(shell $(SED) -e "s/^static.*GitRawRevisionString.*Rev: [0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]\([0-9][0-9]*\).*/\\1/p" -e "s/^0*//" -e d $(SCCSVER) | $(SED) -e 's/^0*//')

RCFLAGS:= --include-dir $(PLATDIR)/win32/misc -D_WIN32 -DFILEVERSIONVALUES=$(SVNMAJOR),$(SVNMINOR),$(SVNREV),$(SVNBUILD) '-DFILEVERSIONSTRING=\"$(SVNMAJOR).$(SVNMINOR).$(SVNREV).$(SVNBUILD)\\0\"'
