#############################################################################
# Common Makefile for Win64 VM using LLVM/Clang compiler, MSVC build tools,
# GNU make/sed/grep, and the Windows 10 SDK.
#
# -> https://github.com/llvm/llvm-project/releases
# -> https://developer.microsoft.com/de-de/windows/downloads/windows-sdk/
# -> https://visualstudio.microsoft.com/de/vs/community/
# -> https://www.msys2.org/
#
# Make sure to either use a Clang from MS Visual Studio or a pre-built
# clang that targets *-pc-windows-msvc. The Clang from MSYS2 pacman will
# target *-w64-windows-gnu . See Makefile for the MSYS2 toolchain.
#
# RECOMMENDED: Start plain MSYS2 shell, run "mvm" script.
# Alternative: Start Native Tools Command Prompt, run SETPATH then MAKE*.BAT.
#
# Copyright (c) Andreas Raab, Eliot Miranda, Marcel Taeumel, et al. 
# Copyright (c) 2020 3D Immersive Collaboration Consulting, LLC
# Copyright (c) 2025 Hasso Plattner Institute, University of Potsdam, Germany
#
# Do make init to allow make -n to function.
#############################################################################

#############################################################################
# Parameters:
# VM the name of the exe to build, defaults to Squeak (=> Squeak.exe)
# VM_NAME the name the VM will print when reporting, defaults to $(VM)
# VMSRCDIR the directory containing the interpreter, optional cogit and interp.h
# CONFIGURATION configuration of VM to build from product, assert & debug
# THREADING whether to build a multi-threaded FFI VM
# COGDEFS supply any command-line defines to use, and may be null.

.PHONY: all
all: default

VM?=Squeak
VM_NAME?=$(VM)
export VM VM_NAME CONFIGURATION COGDEFS

# This Makefile has a two-pass initialization scheme for COGDEFS, which
# sets VM-specific compilation flags such as for multi-threaded and
# debug builds. We encode this by checking whether CONFIGURATION was 
# provided from the outer invocation. We want to avoid expanding COGDEFS
# with the wrong default values in the first, preparatory pass.
ifeq ($(CONFIGURATION),)
	IS_PREPARING:=true
else
	IS_PREPARING:=false
endif

# Is this a Croquet VM (defaults to OGL instead of D3D)?
CROQUET:=-DCROQUET

#############################################################################
# Default locations
#

ifeq ($(THREADING),multi)
	ifeq ($(CONFIGURATION),product)
		BUILD:=buildmt
	else ifeq ($(CONFIGURATION),assert)
		BUILD:=buildmtast
	else
		BUILD:=buildmtdbg
	endif
else
	ifeq ($(CONFIGURATION),product)
		BUILD:=build
	else ifeq ($(CONFIGURATION),assert)
		BUILD:=buildast
	else
		BUILD:=builddbg
	endif
endif

PLUGINSRCDIR:= ../../../src
export PLUGINSRCDIR
OBJDIR:= $(BUILD)/vm

PLATDIR:=../../../platforms
export PLATDIR
CROSSDIR:=$(PLATDIR)/Cross/vm
TPDIR:=$(PLATDIR)/Cross/third-party
export TPDIR
WIN32DIR:=$(PLATDIR)/win32/vm
WIN32PLUGINSDIR:=$(PLATDIR)/win32/plugins
WIN32MISCDIR:=$(PLATDIR)/win32/misc
WIN32UTILDIR:=$(PLATDIR)/win32/util

CROSSSRC:= $(wildcard $(CROSSDIR)/*.c) $(wildcard $(CROSSDIR)/*.cpp)
WIN32SRC:= $(wildcard $(WIN32DIR)/*.c) $(wildcard $(WIN32DIR)/*.cpp)
ifeq ($(THREADING),multi)
MAKERSRC:= $(wildcard $(VMSRCDIR)/[ci]*terpmt.c $(VMSRCDIR)/cogit.c)
else
MAKERSRC:= $(wildcard $(VMSRCDIR)/[ci]*terp.c $(VMSRCDIR)/cogit.c)
endif
VMSRC:= $(notdir $(MAKERSRC) $(WIN32SRC) $(CROSSSRC))

VPATH:= $(VMSRCDIR) $(WIN32DIR) $(CROSSDIR)

#############################################################################
# Toolchain (incl. paths to tools and flags for tools)
#
include ../common/Makefile.WinSDK.tools

#############################################################################
$(shell $(MKDIR) deps >/dev/null) # deps is the dependencies directory

#############################################################################
# The internal (.lib) and external (.dll) plugins
#
include plugins.ext
include plugins.int

LIBS:= $(addprefix $(OBJDIR)/, $(addsuffix .lib, $(INTERNAL_PLUGINS)))
DLLS:= $(addprefix $(OBJDIR)/, $(addsuffix .dll, $(EXTERNAL_PLUGINS)))

ifdef BIT_IDENTICAL_FLOATING_POINT
LIBS:=$(BUILD)/fdlibm/libm.a $(LIBS)
export BIT_IDENTICAL_FLOATING_POINT
endif

.PHONY: libs dlls

libs: $(LIBS)
dlls: $(DLLS)


#############################################################################
# The third-party libraries
#
ifneq ($(THIRDPARTYLIBS),)
include ../common/Makefile.lib.extra
THIRDPARTYPREREQS:=$(THIRDPARTYCACHEDIR) $(THIRDPARTYOUTDIR) 
endif

#############################################################################
# Generic VM source file definitions
#
VMOBJ:=	$(VMSRC:.c=.o)
VMOBJ:= $(addprefix $(OBJDIR)/,$(VMOBJ))

#############################################################################
# SqueakVM definitions
#
VMEXE:=  $(OBJDIR)/$(VM).exe
CONSOLEVMEXE:=  $(OBJDIR)/$(VM)Console.exe
VMDEF:=	$(VM).def
VMMAP:=	$(OBJDIR)/$(VM).map
CONSOLEVMMAP:=	$(OBJDIR)/$(VM)Console.map
VMLIB:=	$(VM).lib
VMRES:=	$(VM).res
VMDEFIN:=$(VM).def.in
BTOBJ:= $(OBJDIR)/btext.o
ETOBJ:= $(OBJDIR)/etext.o
JMPASM:=_setjmp-$(ARCH).asm
JMPOBJ:=$(OBJDIR)/_setjmp-$(ARCH).o

.PRECIOUS: mkNamedPrims.exe

INCLUDES:= -I. -I$(VMSRCDIR) -I$(WIN32DIR) -I$(CROSSDIR) $(XINC)

.SUFFIXES:
.SUFFIXES:	.ccg .cc .c .o .s .i .rc .res .cg .hg .ccg .cpp

#############################################################################
# Common build rules
#

default: product # ensure two-pass initialization, see below
defaultBuild: print-tools print-settings init libs $(VMEXE) $(CONSOLEVMEXE) dlls $(APPPOST)

svnver:
	echo $(RC) $(RCFLAGS)

productmt:
	$(MAKE) -f $(firstword $(MAKEFILE_LIST)) CONFIGURATION=product THREADING=multi $(@,product=) defaultBuild

product:
	$(MAKE) -f $(firstword $(MAKEFILE_LIST)) CONFIGURATION=product THREADING=single $(@,product=) defaultBuild

assertmt:
	$(MAKE) -f $(firstword $(MAKEFILE_LIST)) CONFIGURATION=assert THREADING=multi $(@,assert=) defaultBuild

assert:
	$(MAKE) -f $(firstword $(MAKEFILE_LIST)) CONFIGURATION=assert THREADING=single $(@,assert=) defaultBuild

debugmt:
	$(MAKE) -f $(firstword $(MAKEFILE_LIST)) CONFIGURATION=debug THREADING=multi $(@,debug=) defaultBuild

debug:
	$(MAKE) -f $(firstword $(MAKEFILE_LIST)) CONFIGURATION=debug THREADING=single $(@,debug=) defaultBuild

# Do make init to allow make -n to function.
init: $(THIRDPARTYPREREQS) $(OBJDIR) mkNamedPrims.exe

cleanall:	clean cleanmt cleanast cleanmtast cleandbg cleanmtdbg

clean:
	$(RM) -rf sqNamedPrims.h mkNamedPrims.* LOGF build deps

cleanmt:
	$(RM) -rf sqNamedPrims.h mkNamedPrims.* LOGTF buildmt deps

cleanast:
	$(RM) -rf sqNamedPrims.h mkNamedPrims.* LOGA buildast deps

cleanmtast:
	$(RM) -rf sqNamedPrims.h mkNamedPrims.* LOGTA buildmtast deps

cleandbg:
	$(RM) -rf sqNamedPrims.h mkNamedPrims.* LOGD builddbg deps

cleanmtdbg:
	$(RM) -rf sqNamedPrims.h mkNamedPrims.* LOGTD buildmtdbg deps

nukelibs:
	$(RM) $(LIBS)

nukedlls:
	$(RM) $(DLLS)

.PHONY : print-settings

print-settings:
	$(info ---------------- Makefile settings ------------------)
	$(info CONFIGURATION=$(CONFIGURATION))
	$(info THREADING=$(THREADING))
	$(info VPATH=$(VPATH))
	$(info INCLUDES=$(INCLUDES))
	$(info CFLAGS=$(CFLAGS))
	$(info DEFS=$(DEFS))
	$(info INTERNAL_PLUGINS=$(INTERNAL_PLUGINS))
	$(info EXTERNAL_PLUGINS=$(EXTERNAL_PLUGINS))
	$(info OBJDIR=$(OBJDIR))
	$(info LIBS=$(LIBS))
	$(info DLLS=$(DLLS))
	$(info -----------------------------------------------------)

.PHONY : print-objects

print-objects:
	$(info ---------------- Makefile objects ------------------)
	$(info VMOBJ=$(VMOBJ))
	$(info -----------------------------------------------------)

.PHONY : print-tools

print-tools:
	$(info ---------------- Build tools ------------------------)
	$(info VCToolsBinDir          $(VCToolsBinDir))
	$(info WindowsSDKToolsBinDir  $(WindowsSDKToolsBinDir))
	$(info WindowsSdkDir      $(WindowsSdkDir))
	$(info WindowsSDKVersion  $(WindowsSDKVersion))
	$(info MSYS2_BIN          $(MSYS2_BIN))
	$(info LLVM_BIN           $(LLVM_BIN))
	$(info CC    $(shell which $(CC)))
	$(info ..    $(shell $(CC) --version 2> /dev/null | head -n 1))
	$(info CXX   $(shell which $(CXX)))
	$(info ..    $(shell $(CXX) --version 2> /dev/null | head -n 1))
	$(info LD         $(shell which $(LD) 2> /dev/null))
	$(info LDXX       $(shell which $(LD) 2> /dev/null))
	$(info LIBRARIAN  $(shell which $(LIBRARIAN) 2> /dev/null))
	$(info RC         $(shell which $(RC) 2> /dev/null))
	$(info CVTRES     $(shell which $(CVTRES) 2> /dev/null))
	$(info -----------------------------------------------------)

ignore := $(addsuffix .%, $(basename $(wildcard $(BUILD)/vm/*.ignore)))

mkNamedPrims.exe: $(WIN32UTILDIR)/mkNamedPrims.c
	$(CC) -c $< -o mkNamedPrims.obj
	$(LD) -out:$@ mkNamedPrims.obj -subsystem:console -defaultlib:libcmt

$(BTOBJ):	$(WIN32MISCDIR)/btext.c
	$(CC) -c $< -fomit-frame-pointer -Os -o$@

$(ETOBJ):	$(WIN32MISCDIR)/etext.c
	$(CC) -c $< -fomit-frame-pointer -Os -o$@

$(JMPOBJ):	$(WIN32MISCDIR)/$(JMPASM)
	$(CC) -c $< -o$@

vm:	$(VMEXE) $(LIBS) $(DLLS)

TZ:=$(shell $(MSYS2_BIN)date +%Z)

$(VMEXE): $(OBJDIR) $(THIRDPARTYLIBS) $(VMOBJ) libs resource.o $(BTOBJ) $(ETOBJ) $(JMPOBJ)
	$(CC) -o$(OBJDIR)/version.o $(ALLCFLAGS) -D'TZ="$(TZ)"' -c $(WIN32DIR)/version.c
	$(LD) $(LDFLAGS) -OUT:$(VMEXE) -MAP:$(VMMAP) \
			$(BTOBJ) $(VMOBJ) $(JMPOBJ) resource.o $(filter-out $(call ignore), $(LIBS)) $(STDLIBS) $(ETOBJ)

$(CONSOLEVMEXE): $(VMOBJ) libs resource.o $(BTOBJ) $(ETOBJ) $(JMPOBJ)
	$(CC) -o$(OBJDIR)/version.o $(ALLCFLAGS) -D'TZ="$(TZ)"' -c $(WIN32DIR)/version.c
	$(LD) $(CONSOLELDFLAGS) -OUT:$(CONSOLEVMEXE) -MAP:$(CONSOLEVMMAP) \
			$(BTOBJ) $(VMOBJ) $(JMPOBJ) resource.o $(filter-out $(call ignore), $(LIBS)) $(STDLIBS) $(ETOBJ)

$(OBJDIR):
	@-$(MKDIR) $(BUILD)
	$(MKDIR) $(OBJDIR)
ifneq ($(INTERNAL_PLUGINS),)
	$(MKDIR) $(addprefix $(BUILD)/, $(INTERNAL_PLUGINS))
endif
ifneq ($(EXTERNAL_PLUGINS),)
	$(MKDIR) $(addprefix $(BUILD)/, $(EXTERNAL_PLUGINS))
endif


#############################################################################
# Building plugins
#

.PHONY: $(OBJDIR)/%.lib $(OBJDIR)/%.dll
.PHONY: always
# Check for Makefile in win32 plugins directory otherwise use default Makefile
plugin-makefile = $(realpath $(firstword $(wildcard $(WIN32PLUGINSDIR)/$(1)/Makefile.WinSDK.plugin ../common/Makefile.WinSDK.plugin)))

# Internal plugin.  Build as lib then link in lib
$(OBJDIR)/%.lib: always
	@-$(MKDIR) $(BUILD)/$(*F)
	$(RM) -f $(BUILD)/vm/$(*F).ignore
	$(MAKE) $(MFLAGS) $(SUBMFLAGS) -I../common BUILD=$(BUILD) \
		-f $(call plugin-makefile,$(*F)) \
		LIBNAME=$(*F) INTERNAL_PLUGIN=1 VMSRCDIR=$(VMSRCDIR) \
		COGDEFS="$(COGDEFS) -DSQUEAK_BUILTIN_PLUGIN=$(*F)" $(OBJDIR)/$(*F).lib

# External plugin.  Build as dll and copy to vm dir ($(OBJDIR)).
$(OBJDIR)/%.dll: always
	$(info WILDCARD $(*F): $(wildcard $(BUILD)/$(*F)/*.o))
	@-$(MKDIR) $(BUILD)/$(*F)
	$(RM) -f $(BUILD)/$(*F).ignore
	$(MAKE) $(MFLAGS) $(SUBMFLAGS) -I../common BUILD=$(BUILD) \
		-f $(call plugin-makefile,$(*F)) \
		LIBNAME=$(*F) EXTERNAL_PLUGIN=1 VMSRCDIR=$(VMSRCDIR) \
		JMPOBJ=$(JMPOBJ) VMLIB=$(OBJDIR)/$(VMLIB) \
		COGDEFS="$(COGDEFS) -DSQUEAK_EXTERNAL_PLUGIN=$(*F)" $(OBJDIR)/$(*F).dll

$(BUILD)/fdlibm/libm.a:
	@-mkdir -p $(@D)
	$(MAKE) CC='$(CC)' CFLAGS="$(CFLAGS) -D_IEEE_LIBM" -C $(@D) \
		TP=../../$(TPDIR) -f ../../$(TPDIR)/fdlibm/Makefile.remote


#############################################################################
# Basic rules
#
include ../common/Makefile.WinSDK.rules

# Microsoft (R) Windows (R) Resource Compiler
%.res: %.rc
	$(RC) $(RCFLAGS) -Fo $@ $<

# Microsoft (R) Windows Resource To Object Converter
resource.o:	$(VMRES)
	$(CVTRES) -MACHINE:$(ARCH) -OUT:resource.o $(VMRES)
	$(CP) $(VM).exe.manifest $(OBJDIR)
	$(CP) $(VM).exe.manifest $(OBJDIR)/$(VM)Console.exe.manifest

#############################################################################
# Extra specific dependencies
#
sqNamedPrims.h: plugins.int mkNamedPrims.exe
	./mkNamedPrims.exe $(INTERNAL_PLUGINS) > sqNamedPrims.h

$(OBJDIR)/sqNamedPrims.o:	$(CROSSDIR)/sqNamedPrims.c sqNamedPrims.h
