#############################################################################
# Compilation rules for Mac OS X
#
# See http://make.mad-scientist.net/papers/advanced-auto-dependency-generation
# for an explanation of the dependency management scheme.

# /usr/bin/clang, a.k.a. /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CC := i686-apple-darwin10-llvm-gcc-4.2
CXX := i686-apple-darwin10-llvm-g++-4.2
LD := i686-apple-darwin10-llvm-gcc-4.2
LDCXX := clang++ # For linking c++ bundles

include ../common/Makefile.flags

DEPFLAGS = -MT $@ -MMD -MP -MF deps/$(*F).Td
ALLFLAGS = $(DEPFLAGS) $(WARNINGS) $(CFLAGS)
POSTCOMPILE = sed '/^$$/d' <deps/$(*F).Td | sed '/^.*:$$/d' | sed 's/^build[^/]*/$$(BUILD)/' > deps/$(*F).d; rm deps/$(*F).Td; touch -r $< deps/$(*F).d

$(OBJDIR)/%.o: %.c deps/%.d $(MAKEFILE)
	$(CC) -x c $(ALLFLAGS) $(INCLUDES) -c $< -o $@
	$(POSTCOMPILE)

$(OBJDIR)/%.o: %.m deps/%.d $(MAKEFILE)
	$(CC) -x objective-c $(ALLFLAGS) $(INCLUDES) -c $< -o $@
	$(POSTCOMPILE)

$(OBJDIR)/%.o: %.cpp deps/%.d $(MAKEFILE)
	$(CXX) -std=c++11 -stdlib=libc++ $(ALLFLAGS) $(INCLUDES) -c $< -o $@
	$(POSTCOMPILE)

$(OBJDIR)/%.o: %.mm deps/%.d $(MAKEFILE)
	$(CXX) -std=c++11 -stdlib=libc++ $(ALLFLAGS) $(INCLUDES) -c $< -o $@
	$(POSTCOMPILE)

deps/%.d: ;

.PRECIOUS: deps/%.d $(OBJDIR)/%.air $(OBJDIR)/%.metallib

-include $(patsubst %,deps/%.d,$(notdir $(basename $(VMSRC) $(LIBSRC))))
