SET (USE_LIBFFI)

IF (OPT_without-ffi)
  PLUGIN_DISABLE ()
ELSE ()
  IF (${VM_HOST_CPU} STREQUAL "powerpc" OR ${VM_HOST_CPU} STREQUAL "ppc")
    SET (cpu ppc)
  ELSEIF (${VM_HOST_CPU} MATCHES  "i[3456789]86")
    SET (cpu x86)
  ELSE ()
    SET (USE_LIBFFI 1)
  ENDIF ()

  IF (${VM_HOST_OS} STREQUAL "linux")
    SET (abi sysv)
  ELSEIF (${VM_HOST_OS} MATCHES "darwin.*")
    SET (abi darwin)
  ELSE ()
    SET (USE_LIBFFI 1)
  ENDIF ()

  # PLUGIN_MESSAGE ("detected ${cpu}-${abi}")

  IF (USE_LIBFFI OR NOT EXISTS ${plugin}/${cpu}-${abi}.c OR NOT EXISTS ${plugin}/${cpu}-${abi}-asm.S)
    SET (cpu any)
    SET (abi libffi)
    PLUGIN_MESSAGE ("${cpu}-${abi}")
    PLUGIN_FIND_PACKAGE (LIBFFI libffi)
    IF (NOT LIBFFI_FOUND)
      CHECK_INCLUDE_FILE (ffi.h HAVE_FFI_H)
      CHECK_INCLUDE_FILE (ffi/ffi.h HAVE_FFI_FFI_H)
      IF (NOT HAVE_FFI_H AND NOT HAVE_FFI_FFI_H)
        PLUGIN_DISABLE ()
      ELSE ()
        PLUGIN_REQUIRE_LIBRARY (ffi)
      ENDIF ()
    ENDIF ()
  ENDIF ()
  PLUGIN_SOURCES ("${unix}/plugins/${plugin}/${cpu}-${abi}.c ${unix}/plugins/${plugin}/${cpu}-${abi}-asm.S")
ENDIF ()

CONFIG_DEFINE (HAVE_FFI_H)
CONFIG_DEFINE (HAVE_FFI_FFI_H)
